//HintName: B.TheClass.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

namespace B
{
	partial class TheClass
	{
		[global::System.Runtime.CompilerServices.CompilerGenerated]
		[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
		[global::System.Diagnostics.DebuggerNonUserCode]
		[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Generated code.")]
		public TheClass(global::A.Interface<object, int> i) : base(i)
		{
		}
	}
}
