//HintName: CaptiveTransientProvider.ServiceProvider.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

partial class CaptiveTransientProvider : global::System.IServiceProvider, global::System.IDisposable, CaptiveTransientProvider.IResolver<global::ICaptiveHolder>, CaptiveTransientProvider.IResolver<global::ICaptiveWorker>, CaptiveTransientProvider.IResolver<global::ICaptiveSettings>, CaptiveTransientProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ICaptiveHolder>>, CaptiveTransientProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ICaptiveWorker>>, CaptiveTransientProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ICaptiveSettings>>, CaptiveTransientProvider.IResolver<global::System.IServiceProvider>
{
	private readonly object _lock = new object();
	private global::System.Collections.Generic.List<object>? _disposables;

	private volatile global::ICaptiveHolder? _S0;
	private global::ICaptiveHolder S0() { var service = _S0; if (service is not null) return service; lock (_lock) return (_S0 ??= new global::CaptiveHolder(S1())); }
	private global::ICaptiveWorker S1() => new global::CaptiveWorker(S2());
	private volatile global::ICaptiveSettings? _S2;
	private global::ICaptiveSettings S2() { var service = _S2; if (service is not null) return service; lock (_lock) return (_S2 ??= new global::CaptiveSettings()); }

	private object? Resolve(global::System.Type type, object? key, bool probe)
	{
		if (key is null)
		{
			if (type == typeof(global::ICaptiveHolder)) return probe ? this : (object)(S0());
			if (type == typeof(global::ICaptiveWorker)) return probe ? this : (object)(S1());
			if (type == typeof(global::ICaptiveSettings)) return probe ? this : (object)(S2());
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::ICaptiveHolder>)) return probe ? this : (object)(new global::ICaptiveHolder[] { S0() });
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::ICaptiveWorker>)) return probe ? this : (object)(new global::ICaptiveWorker[] { S1() });
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::ICaptiveSettings>)) return probe ? this : (object)(new global::ICaptiveSettings[] { S2() });
			if (type == typeof(global::System.IServiceProvider)) return probe ? this : (object)(this);
			return null;
		}
		return null;
	}

	private global::System.IServiceProvider? Fallback => null;
	public object? GetService(global::System.Type serviceType) => GetKeyedService(serviceType, null);
	public object? GetKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, false) ?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);
	public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey) => GetKeyedService(serviceType, serviceKey) ?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");
	public T? GetService<T>() => this is CaptiveTransientProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;
	public T GetRequiredService<T>() => this is CaptiveTransientProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);
	global::ICaptiveHolder CaptiveTransientProvider.IResolver<global::ICaptiveHolder>.Get() => S0();
	global::ICaptiveWorker CaptiveTransientProvider.IResolver<global::ICaptiveWorker>.Get() => S1();
	global::ICaptiveSettings CaptiveTransientProvider.IResolver<global::ICaptiveSettings>.Get() => S2();
	global::System.Collections.Generic.IEnumerable<global::ICaptiveHolder> CaptiveTransientProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ICaptiveHolder>>.Get() => new global::ICaptiveHolder[] { S0() };
	global::System.Collections.Generic.IEnumerable<global::ICaptiveWorker> CaptiveTransientProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ICaptiveWorker>>.Get() => new global::ICaptiveWorker[] { S1() };
	global::System.Collections.Generic.IEnumerable<global::ICaptiveSettings> CaptiveTransientProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ICaptiveSettings>>.Get() => new global::ICaptiveSettings[] { S2() };
	global::System.IServiceProvider CaptiveTransientProvider.IResolver<global::System.IServiceProvider>.Get() => this;
	private interface IResolver<T> { T Get(); }
	public bool IsService(global::System.Type serviceType) => IsKeyedService(serviceType, null);
	public bool IsKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, true) != null;
	public Scope CreateScope() => new Scope(this);

	private static T Required<T>(object? service) => service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");
	private T Track<T>(T service)
	{
		if (service is global::System.IDisposable) lock (_lock) (_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
		return service;
	}
	private object[] Drain() { lock (_lock) { var items = _disposables?.ToArray() ?? new object[0]; _disposables = null; global::System.Array.Reverse(items); return items; } }
	public void Dispose() { foreach (var item in Drain()) (item as global::System.IDisposable ?? throw new global::System.InvalidOperationException("'" + item.GetType() + "' only implements IAsyncDisposable, use DisposeAsync.")).Dispose(); }

	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public sealed class Scope : global::System.IServiceProvider, global::System.IDisposable, CaptiveTransientProvider.IResolver<global::ICaptiveHolder>, CaptiveTransientProvider.IResolver<global::ICaptiveWorker>, CaptiveTransientProvider.IResolver<global::ICaptiveSettings>, CaptiveTransientProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ICaptiveHolder>>, CaptiveTransientProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ICaptiveWorker>>, CaptiveTransientProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ICaptiveSettings>>, CaptiveTransientProvider.IResolver<global::System.IServiceProvider>
	{
		private readonly object _lock = new object();
		private global::System.Collections.Generic.List<object>? _disposables;
		private readonly CaptiveTransientProvider _root;
		public Scope(CaptiveTransientProvider root) => _root = root;
		public global::System.IServiceProvider ServiceProvider => this;

		private global::ICaptiveHolder S0() => _root.S0();
		private global::ICaptiveWorker S1() => new global::CaptiveWorker(S2());
		private global::ICaptiveSettings S2() => _root.S2();

		private object? Resolve(global::System.Type type, object? key, bool probe)
		{
			if (key is null)
			{
				if (type == typeof(global::ICaptiveHolder)) return probe ? this : (object)(S0());
				if (type == typeof(global::ICaptiveWorker)) return probe ? this : (object)(S1());
				if (type == typeof(global::ICaptiveSettings)) return probe ? this : (object)(S2());
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::ICaptiveHolder>)) return probe ? this : (object)(new global::ICaptiveHolder[] { S0() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::ICaptiveWorker>)) return probe ? this : (object)(new global::ICaptiveWorker[] { S1() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::ICaptiveSettings>)) return probe ? this : (object)(new global::ICaptiveSettings[] { S2() });
				if (type == typeof(global::System.IServiceProvider)) return probe ? this : (object)(this);
				return null;
			}
			return null;
		}

		private global::System.IServiceProvider? Fallback => null;
		public object? GetService(global::System.Type serviceType) => GetKeyedService(serviceType, null);
		public object? GetKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, false) ?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);
		public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey) => GetKeyedService(serviceType, serviceKey) ?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");
		public T? GetService<T>() => this is CaptiveTransientProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;
		public T GetRequiredService<T>() => this is CaptiveTransientProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);
		global::ICaptiveHolder CaptiveTransientProvider.IResolver<global::ICaptiveHolder>.Get() => S0();
		global::ICaptiveWorker CaptiveTransientProvider.IResolver<global::ICaptiveWorker>.Get() => S1();
		global::ICaptiveSettings CaptiveTransientProvider.IResolver<global::ICaptiveSettings>.Get() => S2();
		global::System.Collections.Generic.IEnumerable<global::ICaptiveHolder> CaptiveTransientProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ICaptiveHolder>>.Get() => new global::ICaptiveHolder[] { S0() };
		global::System.Collections.Generic.IEnumerable<global::ICaptiveWorker> CaptiveTransientProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ICaptiveWorker>>.Get() => new global::ICaptiveWorker[] { S1() };
		global::System.Collections.Generic.IEnumerable<global::ICaptiveSettings> CaptiveTransientProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ICaptiveSettings>>.Get() => new global::ICaptiveSettings[] { S2() };
		global::System.IServiceProvider CaptiveTransientProvider.IResolver<global::System.IServiceProvider>.Get() => this;
		public bool IsService(global::System.Type serviceType) => IsKeyedService(serviceType, null);
		public bool IsKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, true) != null;
		public Scope CreateScope() => new Scope(_root);

		private static T Required<T>(object? service) => service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");
		private T Track<T>(T service)
		{
			if (service is global::System.IDisposable) lock (_lock) (_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
			return service;
		}
		private object[] Drain() { lock (_lock) { var items = _disposables?.ToArray() ?? new object[0]; _disposables = null; global::System.Array.Reverse(items); return items; } }
		public void Dispose() { foreach (var item in Drain()) (item as global::System.IDisposable ?? throw new global::System.InvalidOperationException("'" + item.GetType() + "' only implements IAsyncDisposable, use DisposeAsync.")).Dispose(); }
	}
}
