changelog:
  exclude:
    authors:
      - dependabot
  categories:
    - title: 🐞 Bug Fixes
      labels:
        - bug
    - title: 🏕 Features
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: 👒 Dependencies
      labels:
        - dependencies
