//HintName: ExcludeStaticAndInitialisedFieldsTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class ExcludeStaticAndInitialisedFieldsTest
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public ExcludeStaticAndInitialisedFieldsTest(int s)
	{
		this._s = s;
	}
}
