//HintName: FriendlyParameterNamesTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class FriendlyParameterNamesTest
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public FriendlyParameterNamesTest(
		int _,
		int _2,
		int underscorePrefix,
		int doubleUnderscorePrefix,
		int camelCase,
		int pascalCase
	)
	{
		this._ = _;
		this._2 = _2;
		this._underscorePrefix = underscorePrefix;
		this.__doubleUnderscorePrefix = doubleUnderscorePrefix;
		this.camelCase = camelCase;
		this.PascalCase = pascalCase;
	}
}
