//HintName: A.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class A
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public A(
		global::IServiceE serviceE,
		global::IServiceD serviceD,
		global::IServiceC serviceC,
		global::IServiceB serviceB,
		global::IServiceA serviceA
	) : base(
		serviceE,
		serviceD,
		serviceC,
		serviceB
	)
	{
		this._serviceA = serviceA;
	}
}
