//HintName: InheritanceBaseC.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

partial class InheritanceBaseC
{
	public InheritanceBaseC(global::IExampleA exampleA, global::IExampleB exampleB, global::IExampleC exampleC) : base(exampleA, exampleB)
	{
		this._exampleC = exampleC;
	}
}
