//HintName: InheritanceBaseA.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

partial class InheritanceBaseA
{
	public InheritanceBaseA(global::IExampleA exampleA)
	{
		this._exampleA = exampleA;
	}
}
