//HintName: KeywordsTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class KeywordsTest
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public KeywordsTest(int @base, int @int, int @class, int @private)
	{
		this.@base = @base;
		this.@int = @int;
		this.@class = @class;
		this._private = @private;
	}
}
