//HintName: OuterClass1.OuterRecord1.OuterClass2.MixedNestedClassAndRecordTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class OuterClass1
{
	partial record OuterRecord1
	{
		partial class OuterClass2
		{
			partial record MixedNestedClassAndRecordTest
			{
				[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
				[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
				public MixedNestedClassAndRecordTest(int item)
				{
					this._item = item;
				}
			}
		}
	}
}
