//HintName: Example2.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class Example2
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public Example2(global::IServiceD a, global::IServiceE b, global::IServiceF f) : base(a, b)
	{
		this.f = f;
	}
}
