//HintName: NullableAnnotationTests.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class NullableAnnotationTests
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public NullableAnnotationTests(
		global::IServiceA nullableService,
		global::IServiceB guardedService
	)
	{
		this._nullableService = nullableService;
		this._guardedService = guardedService ?? throw new global::System.ArgumentNullException("guardedService");
	}
}
