//HintName: PostCtorWithArgumentsTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class PostCtorWithArgumentsTest
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public PostCtorWithArgumentsTest(global::IServiceA a, global::IServiceB b)
	{
		this.a = a;
		Initialize(b);
	}
}
