//HintName: PostCtorOptionalDefault.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class PostCtorOptionalDefault
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public PostCtorOptionalDefault(string value = default, global::Flag flag = (global::Flag)0)
	{
		Initialize(value, flag);
	}
}
