//HintName: PostCtorWithMSKeyedServiceTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class PostCtorWithMSKeyedServiceTest
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public PostCtorWithMSKeyedServiceTest(
		[global::Microsoft.Extensions.DependencyInjection.FromKeyedServices("field")] global::IService service,
		[global::Microsoft.Extensions.DependencyInjection.FromKeyedServices("postconstruct")] global::IService postConstructService
	)
	{
		this._service = service;
		Initialize(postConstructService);
	}
}
