//HintName: BaseClass.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class BaseClass
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public BaseClass([global::Microsoft.Extensions.DependencyInjection.FromKeyedServices("base")] global::IService service)
	{
		this._service = service;
	}
}
