//HintName: PostCtorWithRefReadonlyArgumentTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class PostCtorWithRefReadonlyArgumentTest
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public PostCtorWithRefReadonlyArgumentTest(
		global::IServiceA serviceA,
		global::IServiceB serviceB,
		global::IServiceFactory serviceFactory
	)
	{
		this._serviceA = serviceA;
		this._serviceB = serviceB;
		Initialize(serviceFactory, in serviceB);
	}
}
