//HintName: DisabledGuard.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class DisabledGuard
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public DisabledGuard(string value)
	{
		this._value = value;
	}
}
