//HintName: DisabledGuard.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

partial class DisabledGuard
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	public DisabledGuard(string value)
	{
		this._value = value;
	}
}
