//HintName: StreamProvider.ServiceProvider.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

partial class StreamProvider : 
	global::System.IServiceProvider,
	global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory,
	global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService,
	global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider,
	global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService,
	global::System.IDisposable,
	global::System.IAsyncDisposable,
	StreamProvider.IResolver<global::IStream>,
	StreamProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IStream>>,
	StreamProvider.IResolver<global::System.IServiceProvider>,
	StreamProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory>,
	StreamProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService>,
	StreamProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider>,
	StreamProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService>

{
	private readonly object _lock = new object();
	private global::System.Collections.Generic.List<object>? _disposables;

	private volatile global::IStream? _S0;
	private global::IStream S0()
	{
		var service = _S0;
		if (service is not null)
			return service;
		lock (_lock)
			return (_S0 ??= Track<global::IStream>(new global::Stream()));
	}

	private object? Resolve(global::System.Type type, object? key, bool probe)
	{
		if (key is null)
		{
			if (type == typeof(global::IStream))
				return probe ? this : (object)(S0());
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IStream>))
				return probe ? this : (object)(new global::IStream[] { S0() });
			if (type == typeof(global::System.IServiceProvider))
				return probe ? this : (object)(this);
			if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory))
				return probe ? this : (object)(this);
			if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService))
				return probe ? this : (object)(this);
			if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider))
				return probe ? this : (object)(this);
			if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService))
				return probe ? this : (object)(this);
			return null;
		}
		return null;
	}

	private global::System.IServiceProvider? Fallback => null;
	public object? GetService(global::System.Type serviceType) => GetKeyedService(serviceType, null);
	public object? GetKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, false) ?? (serviceKey == null ? Fallback?.GetService(serviceType) : (Fallback as global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider)?.GetKeyedService(serviceType, serviceKey));
	public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey) => GetKeyedService(serviceType, serviceKey) ?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");
	public T? GetService<T>() => this is StreamProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;
	public T GetRequiredService<T>() => this is StreamProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);
	global::IStream StreamProvider.IResolver<global::IStream>.Get() => S0();
	global::System.Collections.Generic.IEnumerable<global::IStream> StreamProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IStream>>.Get() => new global::IStream[] { S0() };
	global::System.IServiceProvider StreamProvider.IResolver<global::System.IServiceProvider>.Get() => this;
	global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory StreamProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory>.Get() => this;
	global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService StreamProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService>.Get() => this;
	global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider StreamProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider>.Get() => this;
	global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService StreamProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService>.Get() => this;
	private interface IResolver<T> { T Get(); }
	public bool IsService(global::System.Type serviceType) => IsKeyedService(serviceType, null);
	public bool IsKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, true) != null || (serviceKey == null ? Fallback is global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService s && s.IsService(serviceType) : Fallback is global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService k && k.IsKeyedService(serviceType, serviceKey));
	public Scope CreateScope() => new Scope(this);
	global::Microsoft.Extensions.DependencyInjection.IServiceScope global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory.CreateScope() => CreateScope();

	private static T Required<T>(object? service) => service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");
	private T Track<T>(T service)
	{
		if (service is global::System.IDisposable || service is global::System.IAsyncDisposable)
			lock (_lock)
				(_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
		return service;
	}
	private object[] Drain()
	{
		lock (_lock)
		{
			var items = _disposables?.ToArray() ?? new object[0];
			_disposables = null;
			global::System.Array.Reverse(items);
			return items;
		}
	}
	public void Dispose()
	{
		foreach (var item in Drain())
			(item as global::System.IDisposable ?? throw new global::System.InvalidOperationException("'" + item.GetType() + "' only implements IAsyncDisposable, use DisposeAsync.")).Dispose();
	}
	public async global::System.Threading.Tasks.ValueTask DisposeAsync()
	{
		foreach (var item in Drain())
			if (item is global::System.IAsyncDisposable d)
				await d.DisposeAsync().ConfigureAwait(false);
			else
				((global::System.IDisposable)item).Dispose();
	}

	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public sealed class Scope : 
		global::System.IServiceProvider,
		global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory,
		global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService,
		global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider,
		global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService,
		global::System.IDisposable,
		global::System.IAsyncDisposable,
		global::Microsoft.Extensions.DependencyInjection.IServiceScope,
		StreamProvider.IResolver<global::IStream>,
		StreamProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IStream>>,
		StreamProvider.IResolver<global::System.IServiceProvider>,
		StreamProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory>,
		StreamProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService>,
		StreamProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider>,
		StreamProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService>
	
	{
		private readonly object _lock = new object();
		private global::System.Collections.Generic.List<object>? _disposables;
		private readonly StreamProvider _root;
		public Scope(StreamProvider root) => _root = root;
		public global::System.IServiceProvider ServiceProvider => this;

		private global::IStream S0() => _root.S0();

		private object? Resolve(global::System.Type type, object? key, bool probe)
		{
			if (key is null)
			{
				if (type == typeof(global::IStream))
					return probe ? this : (object)(S0());
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IStream>))
					return probe ? this : (object)(new global::IStream[] { S0() });
				if (type == typeof(global::System.IServiceProvider))
					return probe ? this : (object)(this);
				if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory))
					return probe ? this : (object)(this);
				if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService))
					return probe ? this : (object)(this);
				if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider))
					return probe ? this : (object)(this);
				if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService))
					return probe ? this : (object)(this);
				return null;
			}
			return null;
		}

		private global::System.IServiceProvider? Fallback => null;
		public object? GetService(global::System.Type serviceType) => GetKeyedService(serviceType, null);
		public object? GetKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, false) ?? (serviceKey == null ? Fallback?.GetService(serviceType) : (Fallback as global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider)?.GetKeyedService(serviceType, serviceKey));
		public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey) => GetKeyedService(serviceType, serviceKey) ?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");
		public T? GetService<T>() => this is StreamProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;
		public T GetRequiredService<T>() => this is StreamProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);
		global::IStream StreamProvider.IResolver<global::IStream>.Get() => S0();
		global::System.Collections.Generic.IEnumerable<global::IStream> StreamProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IStream>>.Get() => new global::IStream[] { S0() };
		global::System.IServiceProvider StreamProvider.IResolver<global::System.IServiceProvider>.Get() => this;
		global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory StreamProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory>.Get() => this;
		global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService StreamProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService>.Get() => this;
		global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider StreamProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider>.Get() => this;
		global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService StreamProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService>.Get() => this;
		public bool IsService(global::System.Type serviceType) => IsKeyedService(serviceType, null);
		public bool IsKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, true) != null || (serviceKey == null ? Fallback is global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService s && s.IsService(serviceType) : Fallback is global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService k && k.IsKeyedService(serviceType, serviceKey));
		public Scope CreateScope() => new Scope(_root);
		global::Microsoft.Extensions.DependencyInjection.IServiceScope global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory.CreateScope() => CreateScope();

		private static T Required<T>(object? service) => service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");
		private T Track<T>(T service)
		{
			if (service is global::System.IDisposable || service is global::System.IAsyncDisposable)
				lock (_lock)
					(_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
			return service;
		}
		private object[] Drain()
		{
			lock (_lock)
			{
				var items = _disposables?.ToArray() ?? new object[0];
				_disposables = null;
				global::System.Array.Reverse(items);
				return items;
			}
		}
		public void Dispose()
		{
			foreach (var item in Drain())
				(item as global::System.IDisposable ?? throw new global::System.InvalidOperationException("'" + item.GetType() + "' only implements IAsyncDisposable, use DisposeAsync.")).Dispose();
		}
		public async global::System.Threading.Tasks.ValueTask DisposeAsync()
		{
			foreach (var item in Drain())
				if (item is global::System.IAsyncDisposable d)
					await d.DisposeAsync().ConfigureAwait(false);
				else
					((global::System.IDisposable)item).Dispose();
		}
	}
}
