//HintName: AbstractClassTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

partial class AbstractClassTest
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("AutoCtor", "0.0.0")]
	public AbstractClassTest(int item)
	{
		this._item = item;
	}
}
