//HintName: BaseClass.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

partial class BaseClass
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("AutoCtor", "0.0.0")]
	public BaseClass(int number, string text) : base(number)
	{
		this._text = text;
	}
}
