//HintName: CClass.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class CClass
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public CClass(global::IExampleA example, global::IExampleB example0, global::IExampleC example1) : base(example, example0)
	{
		this._example = example1;
	}
}
