//HintName: AutoConstructAttribute.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#if AUTOCTOR_EMBED_ATTRIBUTES
namespace AutoCtor
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	public enum GuardSetting
	{
		Default,
		Disabled,
		Enabled
	}
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
	internal sealed class AutoConstructAttribute : global::System.Attribute
	{
		public AutoConstructAttribute(GuardSetting guard = GuardSetting.Default)
		{
		}
	}
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
	internal sealed class AutoPostConstructAttribute : global::System.Attribute
	{
	}
}
#endif
