//HintName: FriendlyParameterNamesTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class FriendlyParameterNamesTest
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public FriendlyParameterNamesTest(
		int underscorePrefix,
		int camelCase,
		int PascalCase
	)
	{
		this._underscorePrefix = underscorePrefix;
		this.camelCase = camelCase;
		this.PascalCase = PascalCase;
	}
}
