//HintName: FriendlyParameterNamesTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

partial class FriendlyParameterNamesTest
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	public FriendlyParameterNamesTest(int underscorePrefix, int camelCase, int PascalCase)
	{
		this._underscorePrefix = underscorePrefix;
		this.camelCase = camelCase;
		this.PascalCase = PascalCase;
	}
}
