//HintName: ConcreteClassWithGenericArg[T2].g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

partial class ConcreteClassWithGenericArg<T2>
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("AutoCtor", "0.0.0")]
	public ConcreteClassWithGenericArg(T2 t) : base(t)
	{
	}
}
