//HintName: GenericBase2[T1, T2].g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

partial class GenericBase2<T1, T2>
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	public GenericBase2(T1 t1, T2 t2)
	{
		this._t1 = t1;
		this._t2 = t2;
	}
}
