//HintName: Guard.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

partial class Guard
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	public Guard(string value)
	{
		this._value = value ?? throw new global::System.ArgumentNullException("value");
	}
}
