//HintName: B.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

partial class B
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	public B(global::IE e, global::ID d, global::IC c, global::IB b) : base(e, d, c)
	{
		this.b = b;
	}
}
