//HintName: D.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

partial class D
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("AutoCtor", "0.0.0")]
	public D(global::IE e, global::ID d) : base(e)
	{
		this.d = d;
	}
}
