//HintName: C.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

partial class C
{
	public C(global::IE e, global::ID d, global::IC c) : base(e, d)
	{
		this.c = c;
	}
}
