//HintName: Base[T2].g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

partial class Base<T2>
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	public Base(global::ILogger<global::Base<T2>> logger)
	{
		this.Logger = logger;
	}
}
