//HintName: ChildKeyedServicesTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class ChildKeyedServicesTest
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public ChildKeyedServicesTest(
		[global::Microsoft.Extensions.DependencyInjection.FromKeyedServices(null)] global::IService @null,
		[global::Microsoft.Extensions.DependencyInjection.FromKeyedServices("key")] global::IService @string,
		[global::Microsoft.Extensions.DependencyInjection.FromKeyedServices(0)] global::IService @int,
		[global::Microsoft.Extensions.DependencyInjection.FromKeyedServices(true)] global::IService @bool,
		[global::Microsoft.Extensions.DependencyInjection.FromKeyedServices(Keys.Default)] global::IService @enum,
		[global::Microsoft.Extensions.DependencyInjection.FromKeyedServices("generic")] global::IService<int> generic,
		global::IService notKeyed
	) : base(
		@null,
		@string,
		@int,
		@bool,
		@enum,
		generic,
		notKeyed
	)
	{
	}
}
