//HintName: Example1.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class Example1
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public Example1(global::IServiceA a, global::IServiceB b, global::IServiceC c) : base(a, b)
	{
		this.c = c;
	}
}
