//HintName: Example2.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

partial class Example2
{
	public Example2(global::ID a, global::IE b, global::IF f) : base(a, b)
	{
		this.f = f;
	}
}
