//HintName: TestNamespace.NamespaceTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestNamespace
{
	partial class NamespaceTest
	{
		public NamespaceTest(int item)
		{
			this._item = item;
		}
	}
}
