//HintName: TestNamespace.NamespaceTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestNamespace
{
	partial class NamespaceTest
	{
		[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		public NamespaceTest(int item)
		{
			this._item = item;
		}
	}
}
