//HintName: TestNamespace.OuterClass1.OuterClass2.NamespaceDoubleNestedClassTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestNamespace
{
	partial class OuterClass1
	{
		partial class OuterClass2
		{
			partial class NamespaceDoubleNestedClassTest
			{
				[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("AutoCtor", "0.0.0")]
				public NamespaceDoubleNestedClassTest(int item)
				{
					this._item = item;
				}
			}
		}
	}
}
