//HintName: PostCtorWithKeyedOutServiceTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class PostCtorWithKeyedOutServiceTest
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public PostCtorWithKeyedOutServiceTest()
	{
		Initialize(out this._service);
	}
}
