//HintName: PostCtorWithOutArgumentTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class PostCtorWithOutArgumentTest
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public PostCtorWithOutArgumentTest(global::IServiceA serviceA, global::IServiceFactory serviceFactory)
	{
		this._serviceA = serviceA;
		Initialise(serviceFactory, out _serviceB);
	}
}
