//HintName: PostCtorWithOptionalArgumentsTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class PostCtorWithOptionalArgumentsTest
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public PostCtorWithOptionalArgumentsTest(global::IServiceA serviceA)
	{
		this._serviceA = serviceA;
	}
}
