//HintName: RecordTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

partial record RecordTest
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	public RecordTest(int item)
	{
		this._item = item;
	}
}
