//HintName: StructTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial struct StructTest
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public StructTest(int item)
	{
		this._item = item;
	}
}
