//HintName: Keyed.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class Keyed
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public Keyed(
		[global::Microsoft.Extensions.DependencyInjection.FromKeyedServices("key")] global::IService keyedService
	)
	{
		this._keyedService = keyedService;
	}
}
