//HintName: PostConstructWithParameter.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class PostConstructWithParameter
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public PostConstructWithParameter(
		global::IService service,
		global::IInitializeService initialiseService
	)
	{
		this._service = service;
		Initialize(initialiseService);
	}
}
