//HintName: PostConstructWithOutParameter.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class PostConstructWithOutParameter
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
	public PostConstructWithOutParameter(
		global::IOtherService otherService,
		global::IServiceProvider services
	)
	{
		this._otherService = otherService;
		Initialize(services, out this._service);
	}
}
