//HintName: ValidationProvider.ServiceProvider.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

partial class ValidationProvider : 
	global::System.IServiceProvider,
	global::System.IDisposable,
	ValidationProvider.IResolver<global::IValidator>,
	ValidationProvider.IResolver<global::IValidationRunner>,
	ValidationProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IValidator>>,
	ValidationProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IValidationRunner>>,
	ValidationProvider.IResolver<global::System.IServiceProvider>

{
	private readonly object _lock = new object();
	private global::System.Collections.Generic.List<object>? _disposables;

	private volatile global::IValidator? _S0;
	private global::IValidator S0()
	{
		var service = _S0;
		if (service is not null)
			return service;
		lock (_lock)
			return (_S0 ??= new global::NameValidator());
	}
	private volatile global::IValidator? _S1;
	private global::IValidator S1()
	{
		var service = _S1;
		if (service is not null)
			return service;
		lock (_lock)
			return (_S1 ??= new global::EmailValidator());
	}
	private volatile global::IValidator? _S2;
	private global::IValidator S2()
	{
		var service = _S2;
		if (service is not null)
			return service;
		lock (_lock)
			return (_S2 ??= new global::AgeValidator());
	}
	private volatile global::IValidationRunner? _S3;
	private global::IValidationRunner S3()
	{
		var service = _S3;
		if (service is not null)
			return service;
		lock (_lock)
			return (_S3 ??= new global::ValidationRunner(new global::IValidator[] { S0(), S1(), S2() }));
	}

	private object? Resolve(global::System.Type type, object? key, bool probe)
	{
		if (key is null)
		{
			if (type == typeof(global::IValidator))
				return probe ? this : (object)(S2());
			if (type == typeof(global::IValidationRunner))
				return probe ? this : (object)(S3());
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IValidator>))
				return probe ? this : (object)(new global::IValidator[] { S0(), S1(), S2() });
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IValidationRunner>))
				return probe ? this : (object)(new global::IValidationRunner[] { S3() });
			if (type == typeof(global::System.IServiceProvider))
				return probe ? this : (object)(this);
			return null;
		}
		return null;
	}

	private global::System.IServiceProvider? Fallback => null;

	public object? GetService(global::System.Type serviceType)
		=> GetKeyedService(serviceType, null);

	public object? GetKeyedService(global::System.Type serviceType, object? serviceKey)
		=> Resolve(serviceType, serviceKey, false)
		?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);

	public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey)
		=> GetKeyedService(serviceType, serviceKey)
		?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");

	public T? GetService<T>()
		=> this is ValidationProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;

	public T GetRequiredService<T>()
		=> this is ValidationProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);

	private interface IResolver<T> { T Get(); }
	global::IValidator ValidationProvider.IResolver<global::IValidator>.Get()
		=> S2();
	global::IValidationRunner ValidationProvider.IResolver<global::IValidationRunner>.Get()
		=> S3();
	global::System.Collections.Generic.IEnumerable<global::IValidator> ValidationProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IValidator>>.Get()
		=> new global::IValidator[] { S0(), S1(), S2() };
	global::System.Collections.Generic.IEnumerable<global::IValidationRunner> ValidationProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IValidationRunner>>.Get()
		=> new global::IValidationRunner[] { S3() };
	global::System.IServiceProvider ValidationProvider.IResolver<global::System.IServiceProvider>.Get()
		=> this;

	public bool IsService(global::System.Type serviceType)
		=> IsKeyedService(serviceType, null);

	public bool IsKeyedService(global::System.Type serviceType, object? serviceKey)
		=> Resolve(serviceType, serviceKey, true) != null;

	public Scope CreateScope() => new Scope(this);

	private static T Required<T>(object? service)
		=> service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");

	private T Track<T>(T service)
	{
		if (service is global::System.IDisposable)
			lock (_lock)
				(_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
		return service;
	}

	private object[] Drain()
	{
		lock (_lock)
		{
			var items = _disposables?.ToArray() ?? new object[0];
			_disposables = null;
			global::System.Array.Reverse(items);
			return items;
		}
	}

	public void Dispose()
	{
		foreach (var item in Drain())
		{
			if (item is global::System.IDisposable disposable)
			{
				disposable.Dispose();
			}
		}
	}

	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public sealed class Scope : 
		global::System.IServiceProvider,
		global::System.IDisposable,
		ValidationProvider.IResolver<global::IValidator>,
		ValidationProvider.IResolver<global::IValidationRunner>,
		ValidationProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IValidator>>,
		ValidationProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IValidationRunner>>,
		ValidationProvider.IResolver<global::System.IServiceProvider>
	
	{
		private readonly object _lock = new object();
		private global::System.Collections.Generic.List<object>? _disposables;
		private readonly ValidationProvider _root;
		public Scope(ValidationProvider root) => _root = root;
		public global::System.IServiceProvider ServiceProvider => this;

		private global::IValidator S0() => _root.S0();
		private global::IValidator S1() => _root.S1();
		private global::IValidator S2() => _root.S2();
		private global::IValidationRunner S3() => _root.S3();

		private object? Resolve(global::System.Type type, object? key, bool probe)
		{
			if (key is null)
			{
				if (type == typeof(global::IValidator))
					return probe ? this : (object)(S2());
				if (type == typeof(global::IValidationRunner))
					return probe ? this : (object)(S3());
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IValidator>))
					return probe ? this : (object)(new global::IValidator[] { S0(), S1(), S2() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IValidationRunner>))
					return probe ? this : (object)(new global::IValidationRunner[] { S3() });
				if (type == typeof(global::System.IServiceProvider))
					return probe ? this : (object)(this);
				return null;
			}
			return null;
		}

		private global::System.IServiceProvider? Fallback => null;

		public object? GetService(global::System.Type serviceType)
			=> GetKeyedService(serviceType, null);

		public object? GetKeyedService(global::System.Type serviceType, object? serviceKey)
			=> Resolve(serviceType, serviceKey, false)
			?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);

		public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey)
			=> GetKeyedService(serviceType, serviceKey)
			?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");

		public T? GetService<T>()
			=> this is ValidationProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;

		public T GetRequiredService<T>()
			=> this is ValidationProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);

		global::IValidator ValidationProvider.IResolver<global::IValidator>.Get()
			=> S2();
		global::IValidationRunner ValidationProvider.IResolver<global::IValidationRunner>.Get()
			=> S3();
		global::System.Collections.Generic.IEnumerable<global::IValidator> ValidationProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IValidator>>.Get()
			=> new global::IValidator[] { S0(), S1(), S2() };
		global::System.Collections.Generic.IEnumerable<global::IValidationRunner> ValidationProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IValidationRunner>>.Get()
			=> new global::IValidationRunner[] { S3() };
		global::System.IServiceProvider ValidationProvider.IResolver<global::System.IServiceProvider>.Get()
			=> this;

		public bool IsService(global::System.Type serviceType)
			=> IsKeyedService(serviceType, null);

		public bool IsKeyedService(global::System.Type serviceType, object? serviceKey)
			=> Resolve(serviceType, serviceKey, true) != null;

		public Scope CreateScope() => new Scope(_root);

		private static T Required<T>(object? service)
			=> service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");

		private T Track<T>(T service)
		{
			if (service is global::System.IDisposable)
				lock (_lock)
					(_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
			return service;
		}

		private object[] Drain()
		{
			lock (_lock)
			{
				var items = _disposables?.ToArray() ?? new object[0];
				_disposables = null;
				global::System.Array.Reverse(items);
				return items;
			}
		}

		public void Dispose()
		{
			foreach (var item in Drain())
			{
				if (item is global::System.IDisposable disposable)
				{
					disposable.Dispose();
				}
			}
		}
	}
}
