//HintName: CacheProvider.ServiceProvider.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

partial class CacheProvider : 
	global::System.IServiceProvider,
	global::System.IDisposable,
	CacheProvider.IResolver<global::IClock>,
	CacheProvider.IResolver<global::IReportService>,
	CacheProvider.IResolver<global::ICache<global::Report>>,
	CacheProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IClock>>,
	CacheProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IReportService>>,
	CacheProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ICache<global::Report>>>,
	CacheProvider.IResolver<global::System.IServiceProvider>

{
	private readonly object _lock = new object();
	private global::System.Collections.Generic.List<object>? _disposables;

	private volatile global::IClock? _S0;
	private global::IClock S0()
	{
		var service = _S0;
		if (service is not null)
			return service;
		lock (_lock)
			return (_S0 ??= new global::SystemClock());
	}
	private volatile global::IReportService? _S1;
	private global::IReportService S1()
	{
		var service = _S1;
		if (service is not null)
			return service;
		lock (_lock)
			return (_S1 ??= new global::ReportService(S2()));
	}
	private volatile global::ICache<global::Report>? _S2;
	private global::ICache<global::Report> S2()
	{
		var service = _S2;
		if (service is not null)
			return service;
		lock (_lock)
			return (_S2 ??= new global::Cache<global::Report>(S0()));
	}

	private object? Resolve(global::System.Type type, object? key, bool probe)
	{
		if (key is null)
		{
			if (type == typeof(global::IClock))
				return probe ? this : (object)(S0());
			if (type == typeof(global::IReportService))
				return probe ? this : (object)(S1());
			if (type == typeof(global::ICache<global::Report>))
				return probe ? this : (object)(S2());
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IClock>))
				return probe ? this : (object)(new global::IClock[] { S0() });
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IReportService>))
				return probe ? this : (object)(new global::IReportService[] { S1() });
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::ICache<global::Report>>))
				return probe ? this : (object)(new global::ICache<global::Report>[] { S2() });
			if (type == typeof(global::System.IServiceProvider))
				return probe ? this : (object)(this);
			return null;
		}
		return null;
	}

	private global::System.IServiceProvider? Fallback => null;

	public object? GetService(global::System.Type serviceType)
		=> GetKeyedService(serviceType, null);

	public object? GetKeyedService(global::System.Type serviceType, object? serviceKey)
		=> Resolve(serviceType, serviceKey, false)
		?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);

	public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey)
		=> GetKeyedService(serviceType, serviceKey)
		?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");

	public T? GetService<T>()
		=> this is CacheProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;

	public T GetRequiredService<T>()
		=> this is CacheProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);

	private interface IResolver<T> { T Get(); }
	global::IClock CacheProvider.IResolver<global::IClock>.Get()
		=> S0();
	global::IReportService CacheProvider.IResolver<global::IReportService>.Get()
		=> S1();
	global::ICache<global::Report> CacheProvider.IResolver<global::ICache<global::Report>>.Get()
		=> S2();
	global::System.Collections.Generic.IEnumerable<global::IClock> CacheProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IClock>>.Get()
		=> new global::IClock[] { S0() };
	global::System.Collections.Generic.IEnumerable<global::IReportService> CacheProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IReportService>>.Get()
		=> new global::IReportService[] { S1() };
	global::System.Collections.Generic.IEnumerable<global::ICache<global::Report>> CacheProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ICache<global::Report>>>.Get()
		=> new global::ICache<global::Report>[] { S2() };
	global::System.IServiceProvider CacheProvider.IResolver<global::System.IServiceProvider>.Get()
		=> this;

	public bool IsService(global::System.Type serviceType)
		=> IsKeyedService(serviceType, null);

	public bool IsKeyedService(global::System.Type serviceType, object? serviceKey)
		=> Resolve(serviceType, serviceKey, true) != null;

	public Scope CreateScope() => new Scope(this);

	private static T Required<T>(object? service)
		=> service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");

	private T Track<T>(T service)
	{
		if (service is global::System.IDisposable)
			lock (_lock)
				(_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
		return service;
	}

	private object[] Drain()
	{
		lock (_lock)
		{
			var items = _disposables?.ToArray() ?? new object[0];
			_disposables = null;
			global::System.Array.Reverse(items);
			return items;
		}
	}

	public void Dispose()
	{
		foreach (var item in Drain())
		{
			if (item is global::System.IDisposable disposable)
			{
				disposable.Dispose();
			}
		}
	}

	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public sealed class Scope : 
		global::System.IServiceProvider,
		global::System.IDisposable,
		CacheProvider.IResolver<global::IClock>,
		CacheProvider.IResolver<global::IReportService>,
		CacheProvider.IResolver<global::ICache<global::Report>>,
		CacheProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IClock>>,
		CacheProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IReportService>>,
		CacheProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ICache<global::Report>>>,
		CacheProvider.IResolver<global::System.IServiceProvider>
	
	{
		private readonly object _lock = new object();
		private global::System.Collections.Generic.List<object>? _disposables;
		private readonly CacheProvider _root;
		public Scope(CacheProvider root) => _root = root;
		public global::System.IServiceProvider ServiceProvider => this;

		private global::IClock S0() => _root.S0();
		private global::IReportService S1() => _root.S1();
		private global::ICache<global::Report> S2() => _root.S2();

		private object? Resolve(global::System.Type type, object? key, bool probe)
		{
			if (key is null)
			{
				if (type == typeof(global::IClock))
					return probe ? this : (object)(S0());
				if (type == typeof(global::IReportService))
					return probe ? this : (object)(S1());
				if (type == typeof(global::ICache<global::Report>))
					return probe ? this : (object)(S2());
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IClock>))
					return probe ? this : (object)(new global::IClock[] { S0() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IReportService>))
					return probe ? this : (object)(new global::IReportService[] { S1() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::ICache<global::Report>>))
					return probe ? this : (object)(new global::ICache<global::Report>[] { S2() });
				if (type == typeof(global::System.IServiceProvider))
					return probe ? this : (object)(this);
				return null;
			}
			return null;
		}

		private global::System.IServiceProvider? Fallback => null;

		public object? GetService(global::System.Type serviceType)
			=> GetKeyedService(serviceType, null);

		public object? GetKeyedService(global::System.Type serviceType, object? serviceKey)
			=> Resolve(serviceType, serviceKey, false)
			?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);

		public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey)
			=> GetKeyedService(serviceType, serviceKey)
			?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");

		public T? GetService<T>()
			=> this is CacheProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;

		public T GetRequiredService<T>()
			=> this is CacheProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);

		global::IClock CacheProvider.IResolver<global::IClock>.Get()
			=> S0();
		global::IReportService CacheProvider.IResolver<global::IReportService>.Get()
			=> S1();
		global::ICache<global::Report> CacheProvider.IResolver<global::ICache<global::Report>>.Get()
			=> S2();
		global::System.Collections.Generic.IEnumerable<global::IClock> CacheProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IClock>>.Get()
			=> new global::IClock[] { S0() };
		global::System.Collections.Generic.IEnumerable<global::IReportService> CacheProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IReportService>>.Get()
			=> new global::IReportService[] { S1() };
		global::System.Collections.Generic.IEnumerable<global::ICache<global::Report>> CacheProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ICache<global::Report>>>.Get()
			=> new global::ICache<global::Report>[] { S2() };
		global::System.IServiceProvider CacheProvider.IResolver<global::System.IServiceProvider>.Get()
			=> this;

		public bool IsService(global::System.Type serviceType)
			=> IsKeyedService(serviceType, null);

		public bool IsKeyedService(global::System.Type serviceType, object? serviceKey)
			=> Resolve(serviceType, serviceKey, true) != null;

		public Scope CreateScope() => new Scope(_root);

		private static T Required<T>(object? service)
			=> service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");

		private T Track<T>(T service)
		{
			if (service is global::System.IDisposable)
				lock (_lock)
					(_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
			return service;
		}

		private object[] Drain()
		{
			lock (_lock)
			{
				var items = _disposables?.ToArray() ?? new object[0];
				_disposables = null;
				global::System.Array.Reverse(items);
				return items;
			}
		}

		public void Dispose()
		{
			foreach (var item in Drain())
			{
				if (item is global::System.IDisposable disposable)
				{
					disposable.Dispose();
				}
			}
		}
	}
}
