//HintName: PipelineProvider.ServiceProvider.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

partial class PipelineProvider : 
	global::System.IServiceProvider,
	global::System.IDisposable,
	PipelineProvider.IResolver<global::IPipeline>,
	PipelineProvider.IResolver<global::IHandler<global::Command>>,
	PipelineProvider.IResolver<global::IValidator<global::Command>>,
	PipelineProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IPipeline>>,
	PipelineProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::Command>>>,
	PipelineProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IValidator<global::Command>>>,
	PipelineProvider.IResolver<global::System.IServiceProvider>

{
	private readonly object _lock = new object();
	private global::System.Collections.Generic.List<object>? _disposables;

	private volatile global::IPipeline? _S0;
	private global::IPipeline S0()
	{
		var service = _S0;
		if (service is not null)
			return service;
		lock (_lock)
			return (_S0 ??= new global::Pipeline(S1()));
	}
	private volatile global::IHandler<global::Command>? _S1;
	private global::IHandler<global::Command> S1()
	{
		var service = _S1;
		if (service is not null)
			return service;
		lock (_lock)
			return (_S1 ??= new global::Handler<global::Command>(S2()));
	}
	private volatile global::IValidator<global::Command>? _S2;
	private global::IValidator<global::Command> S2()
	{
		var service = _S2;
		if (service is not null)
			return service;
		lock (_lock)
			return (_S2 ??= new global::Validator<global::Command>());
	}

	private object? Resolve(global::System.Type type, object? key, bool probe)
	{
		if (key is null)
		{
			if (type == typeof(global::IPipeline))
				return probe ? this : (object)(S0());
			if (type == typeof(global::IHandler<global::Command>))
				return probe ? this : (object)(S1());
			if (type == typeof(global::IValidator<global::Command>))
				return probe ? this : (object)(S2());
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IPipeline>))
				return probe ? this : (object)(new global::IPipeline[] { S0() });
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IHandler<global::Command>>))
				return probe ? this : (object)(new global::IHandler<global::Command>[] { S1() });
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IValidator<global::Command>>))
				return probe ? this : (object)(new global::IValidator<global::Command>[] { S2() });
			if (type == typeof(global::System.IServiceProvider))
				return probe ? this : (object)(this);
			return null;
		}
		return null;
	}

	private global::System.IServiceProvider? Fallback => null;

	public object? GetService(global::System.Type serviceType)
		=> GetKeyedService(serviceType, null);

	public object? GetKeyedService(global::System.Type serviceType, object? serviceKey)
		=> Resolve(serviceType, serviceKey, false)
		?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);

	public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey)
		=> GetKeyedService(serviceType, serviceKey)
		?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");

	public T? GetService<T>()
		=> this is PipelineProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;

	public T GetRequiredService<T>()
		=> this is PipelineProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);

	private interface IResolver<T> { T Get(); }
	global::IPipeline PipelineProvider.IResolver<global::IPipeline>.Get()
		=> S0();
	global::IHandler<global::Command> PipelineProvider.IResolver<global::IHandler<global::Command>>.Get()
		=> S1();
	global::IValidator<global::Command> PipelineProvider.IResolver<global::IValidator<global::Command>>.Get()
		=> S2();
	global::System.Collections.Generic.IEnumerable<global::IPipeline> PipelineProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IPipeline>>.Get()
		=> new global::IPipeline[] { S0() };
	global::System.Collections.Generic.IEnumerable<global::IHandler<global::Command>> PipelineProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::Command>>>.Get()
		=> new global::IHandler<global::Command>[] { S1() };
	global::System.Collections.Generic.IEnumerable<global::IValidator<global::Command>> PipelineProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IValidator<global::Command>>>.Get()
		=> new global::IValidator<global::Command>[] { S2() };
	global::System.IServiceProvider PipelineProvider.IResolver<global::System.IServiceProvider>.Get()
		=> this;

	public bool IsService(global::System.Type serviceType)
		=> IsKeyedService(serviceType, null);

	public bool IsKeyedService(global::System.Type serviceType, object? serviceKey)
		=> Resolve(serviceType, serviceKey, true) != null;

	public Scope CreateScope() => new Scope(this);

	private static T Required<T>(object? service)
		=> service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");

	private T Track<T>(T service)
	{
		if (service is global::System.IDisposable)
			lock (_lock)
				(_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
		return service;
	}

	private object[] Drain()
	{
		lock (_lock)
		{
			var items = _disposables?.ToArray() ?? new object[0];
			_disposables = null;
			global::System.Array.Reverse(items);
			return items;
		}
	}

	public void Dispose()
	{
		foreach (var item in Drain())
		{
			if (item is global::System.IDisposable disposable)
			{
				disposable.Dispose();
			}
		}
	}

	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public sealed class Scope : 
		global::System.IServiceProvider,
		global::System.IDisposable,
		PipelineProvider.IResolver<global::IPipeline>,
		PipelineProvider.IResolver<global::IHandler<global::Command>>,
		PipelineProvider.IResolver<global::IValidator<global::Command>>,
		PipelineProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IPipeline>>,
		PipelineProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::Command>>>,
		PipelineProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IValidator<global::Command>>>,
		PipelineProvider.IResolver<global::System.IServiceProvider>
	
	{
		private readonly object _lock = new object();
		private global::System.Collections.Generic.List<object>? _disposables;
		private readonly PipelineProvider _root;
		public Scope(PipelineProvider root) => _root = root;
		public global::System.IServiceProvider ServiceProvider => this;

		private global::IPipeline S0() => _root.S0();
		private global::IHandler<global::Command> S1() => _root.S1();
		private global::IValidator<global::Command> S2() => _root.S2();

		private object? Resolve(global::System.Type type, object? key, bool probe)
		{
			if (key is null)
			{
				if (type == typeof(global::IPipeline))
					return probe ? this : (object)(S0());
				if (type == typeof(global::IHandler<global::Command>))
					return probe ? this : (object)(S1());
				if (type == typeof(global::IValidator<global::Command>))
					return probe ? this : (object)(S2());
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IPipeline>))
					return probe ? this : (object)(new global::IPipeline[] { S0() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IHandler<global::Command>>))
					return probe ? this : (object)(new global::IHandler<global::Command>[] { S1() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IValidator<global::Command>>))
					return probe ? this : (object)(new global::IValidator<global::Command>[] { S2() });
				if (type == typeof(global::System.IServiceProvider))
					return probe ? this : (object)(this);
				return null;
			}
			return null;
		}

		private global::System.IServiceProvider? Fallback => null;

		public object? GetService(global::System.Type serviceType)
			=> GetKeyedService(serviceType, null);

		public object? GetKeyedService(global::System.Type serviceType, object? serviceKey)
			=> Resolve(serviceType, serviceKey, false)
			?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);

		public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey)
			=> GetKeyedService(serviceType, serviceKey)
			?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");

		public T? GetService<T>()
			=> this is PipelineProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;

		public T GetRequiredService<T>()
			=> this is PipelineProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);

		global::IPipeline PipelineProvider.IResolver<global::IPipeline>.Get()
			=> S0();
		global::IHandler<global::Command> PipelineProvider.IResolver<global::IHandler<global::Command>>.Get()
			=> S1();
		global::IValidator<global::Command> PipelineProvider.IResolver<global::IValidator<global::Command>>.Get()
			=> S2();
		global::System.Collections.Generic.IEnumerable<global::IPipeline> PipelineProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IPipeline>>.Get()
			=> new global::IPipeline[] { S0() };
		global::System.Collections.Generic.IEnumerable<global::IHandler<global::Command>> PipelineProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::Command>>>.Get()
			=> new global::IHandler<global::Command>[] { S1() };
		global::System.Collections.Generic.IEnumerable<global::IValidator<global::Command>> PipelineProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IValidator<global::Command>>>.Get()
			=> new global::IValidator<global::Command>[] { S2() };
		global::System.IServiceProvider PipelineProvider.IResolver<global::System.IServiceProvider>.Get()
			=> this;

		public bool IsService(global::System.Type serviceType)
			=> IsKeyedService(serviceType, null);

		public bool IsKeyedService(global::System.Type serviceType, object? serviceKey)
			=> Resolve(serviceType, serviceKey, true) != null;

		public Scope CreateScope() => new Scope(_root);

		private static T Required<T>(object? service)
			=> service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");

		private T Track<T>(T service)
		{
			if (service is global::System.IDisposable)
				lock (_lock)
					(_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
			return service;
		}

		private object[] Drain()
		{
			lock (_lock)
			{
				var items = _disposables?.ToArray() ?? new object[0];
				_disposables = null;
				global::System.Array.Reverse(items);
				return items;
			}
		}

		public void Dispose()
		{
			foreach (var item in Drain())
			{
				if (item is global::System.IDisposable disposable)
				{
					disposable.Dispose();
				}
			}
		}
	}
}
