//HintName: SubHandler[T].g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class SubHandler<T>
{
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public SubHandler(global::ISubValidator<T> validator)
	{
		this._validator = validator;
	}
}
