//HintName: RepositoryProvider.ServiceProvider.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

partial class RepositoryProvider : 
	global::System.IServiceProvider,
	global::System.IDisposable,
	RepositoryProvider.IResolver<global::IDbSession>,
	RepositoryProvider.IResolver<global::IUserReport>,
	RepositoryProvider.IResolver<global::IRepository<global::User>>,
	RepositoryProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IDbSession>>,
	RepositoryProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IUserReport>>,
	RepositoryProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IRepository<global::User>>>,
	RepositoryProvider.IResolver<global::System.IServiceProvider>

{
	private readonly object _lock = new object();
	private global::System.Collections.Generic.List<object>? _disposables;

	private volatile global::IDbSession? _S0;
	private global::IDbSession S0()
	{
		var service = _S0;
		if (service is not null)
			return service;
		lock (_lock)
			return (_S0 ??= new global::DbSession());
	}
	private volatile global::IUserReport? _S1;
	private global::IUserReport S1()
	{
		var service = _S1;
		if (service is not null)
			return service;
		lock (_lock)
			return (_S1 ??= new global::UserReport(S2()));
	}
	private volatile global::IRepository<global::User>? _S2;
	private global::IRepository<global::User> S2()
	{
		var service = _S2;
		if (service is not null)
			return service;
		lock (_lock)
			return (_S2 ??= new global::Repository<global::User>(S0()));
	}

	private object? Resolve(global::System.Type type, object? key, bool probe)
	{
		if (key is null)
		{
			if (type == typeof(global::IDbSession))
				return probe ? this : (object)(S0());
			if (type == typeof(global::IUserReport))
				return probe ? this : (object)(S1());
			if (type == typeof(global::IRepository<global::User>))
				return probe ? this : (object)(S2());
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IDbSession>))
				return probe ? this : (object)(new global::IDbSession[] { S0() });
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IUserReport>))
				return probe ? this : (object)(new global::IUserReport[] { S1() });
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IRepository<global::User>>))
				return probe ? this : (object)(new global::IRepository<global::User>[] { S2() });
			if (type == typeof(global::System.IServiceProvider))
				return probe ? this : (object)(this);
			return null;
		}
		return null;
	}

	private global::System.IServiceProvider? Fallback => null;
	public object? GetService(global::System.Type serviceType) => GetKeyedService(serviceType, null);
	public object? GetKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, false) ?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);
	public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey) => GetKeyedService(serviceType, serviceKey) ?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");
	public T? GetService<T>() => this is RepositoryProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;
	public T GetRequiredService<T>() => this is RepositoryProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);
	global::IDbSession RepositoryProvider.IResolver<global::IDbSession>.Get() => S0();
	global::IUserReport RepositoryProvider.IResolver<global::IUserReport>.Get() => S1();
	global::IRepository<global::User> RepositoryProvider.IResolver<global::IRepository<global::User>>.Get() => S2();
	global::System.Collections.Generic.IEnumerable<global::IDbSession> RepositoryProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IDbSession>>.Get() => new global::IDbSession[] { S0() };
	global::System.Collections.Generic.IEnumerable<global::IUserReport> RepositoryProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IUserReport>>.Get() => new global::IUserReport[] { S1() };
	global::System.Collections.Generic.IEnumerable<global::IRepository<global::User>> RepositoryProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IRepository<global::User>>>.Get() => new global::IRepository<global::User>[] { S2() };
	global::System.IServiceProvider RepositoryProvider.IResolver<global::System.IServiceProvider>.Get() => this;
	private interface IResolver<T> { T Get(); }
	public bool IsService(global::System.Type serviceType) => IsKeyedService(serviceType, null);
	public bool IsKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, true) != null;
	public Scope CreateScope() => new Scope(this);

	private static T Required<T>(object? service) => service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");
	private T Track<T>(T service)
	{
		if (service is global::System.IDisposable)
			lock (_lock)
				(_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
		return service;
	}
	private object[] Drain()
	{
		lock (_lock)
		{
			var items = _disposables?.ToArray() ?? new object[0];
			_disposables = null;
			global::System.Array.Reverse(items);
			return items;
		}
	}
	public void Dispose()
	{
		foreach (var item in Drain())
			(item as global::System.IDisposable ?? throw new global::System.InvalidOperationException("'" + item.GetType() + "' only implements IAsyncDisposable, use DisposeAsync.")).Dispose();
	}

	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public sealed class Scope : 
		global::System.IServiceProvider,
		global::System.IDisposable,
		RepositoryProvider.IResolver<global::IDbSession>,
		RepositoryProvider.IResolver<global::IUserReport>,
		RepositoryProvider.IResolver<global::IRepository<global::User>>,
		RepositoryProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IDbSession>>,
		RepositoryProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IUserReport>>,
		RepositoryProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IRepository<global::User>>>,
		RepositoryProvider.IResolver<global::System.IServiceProvider>
	
	{
		private readonly object _lock = new object();
		private global::System.Collections.Generic.List<object>? _disposables;
		private readonly RepositoryProvider _root;
		public Scope(RepositoryProvider root) => _root = root;
		public global::System.IServiceProvider ServiceProvider => this;

		private global::IDbSession S0() => _root.S0();
		private global::IUserReport S1() => _root.S1();
		private global::IRepository<global::User> S2() => _root.S2();

		private object? Resolve(global::System.Type type, object? key, bool probe)
		{
			if (key is null)
			{
				if (type == typeof(global::IDbSession))
					return probe ? this : (object)(S0());
				if (type == typeof(global::IUserReport))
					return probe ? this : (object)(S1());
				if (type == typeof(global::IRepository<global::User>))
					return probe ? this : (object)(S2());
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IDbSession>))
					return probe ? this : (object)(new global::IDbSession[] { S0() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IUserReport>))
					return probe ? this : (object)(new global::IUserReport[] { S1() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IRepository<global::User>>))
					return probe ? this : (object)(new global::IRepository<global::User>[] { S2() });
				if (type == typeof(global::System.IServiceProvider))
					return probe ? this : (object)(this);
				return null;
			}
			return null;
		}

		private global::System.IServiceProvider? Fallback => null;
		public object? GetService(global::System.Type serviceType) => GetKeyedService(serviceType, null);
		public object? GetKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, false) ?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);
		public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey) => GetKeyedService(serviceType, serviceKey) ?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");
		public T? GetService<T>() => this is RepositoryProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;
		public T GetRequiredService<T>() => this is RepositoryProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);
		global::IDbSession RepositoryProvider.IResolver<global::IDbSession>.Get() => S0();
		global::IUserReport RepositoryProvider.IResolver<global::IUserReport>.Get() => S1();
		global::IRepository<global::User> RepositoryProvider.IResolver<global::IRepository<global::User>>.Get() => S2();
		global::System.Collections.Generic.IEnumerable<global::IDbSession> RepositoryProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IDbSession>>.Get() => new global::IDbSession[] { S0() };
		global::System.Collections.Generic.IEnumerable<global::IUserReport> RepositoryProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IUserReport>>.Get() => new global::IUserReport[] { S1() };
		global::System.Collections.Generic.IEnumerable<global::IRepository<global::User>> RepositoryProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IRepository<global::User>>>.Get() => new global::IRepository<global::User>[] { S2() };
		global::System.IServiceProvider RepositoryProvider.IResolver<global::System.IServiceProvider>.Get() => this;
		public bool IsService(global::System.Type serviceType) => IsKeyedService(serviceType, null);
		public bool IsKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, true) != null;
		public Scope CreateScope() => new Scope(_root);

		private static T Required<T>(object? service) => service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");
		private T Track<T>(T service)
		{
			if (service is global::System.IDisposable)
				lock (_lock)
					(_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
			return service;
		}
		private object[] Drain()
		{
			lock (_lock)
			{
				var items = _disposables?.ToArray() ?? new object[0];
				_disposables = null;
				global::System.Array.Reverse(items);
				return items;
			}
		}
		public void Dispose()
		{
			foreach (var item in Drain())
				(item as global::System.IDisposable ?? throw new global::System.InvalidOperationException("'" + item.GetType() + "' only implements IAsyncDisposable, use DisposeAsync.")).Dispose();
		}
	}
}
