//HintName: HandlerProvider.ServiceProvider.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

partial class HandlerProvider : global::System.IServiceProvider, global::System.IDisposable, HandlerProvider.IResolver<global::IHandler<global::CancelOrder>>, HandlerProvider.IResolver<global::IHandler<global::CreateOrder>>, HandlerProvider.IResolver<global::IDispatcher>, HandlerProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::CancelOrder>>>, HandlerProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::CreateOrder>>>, HandlerProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IDispatcher>>, HandlerProvider.IResolver<global::System.IServiceProvider>
{
	private readonly object _lock = new object();
	private global::System.Collections.Generic.List<object>? _disposables;

	private global::IHandler<global::CancelOrder> S0() => new global::CancelOrderHandler();
	private global::IHandler<global::CreateOrder> S1() => new global::CreateOrderHandler();
	private global::IDispatcher S2() => new global::Dispatcher(S1(), S0());

	private object? Resolve(global::System.Type type, object? key, bool probe)
	{
		if (key is null)
		{
			if (type == typeof(global::IHandler<global::CancelOrder>)) return probe ? this : (object)(S0());
			if (type == typeof(global::IHandler<global::CreateOrder>)) return probe ? this : (object)(S1());
			if (type == typeof(global::IDispatcher)) return probe ? this : (object)(S2());
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IHandler<global::CancelOrder>>)) return probe ? this : (object)(new global::IHandler<global::CancelOrder>[] { S0() });
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IHandler<global::CreateOrder>>)) return probe ? this : (object)(new global::IHandler<global::CreateOrder>[] { S1() });
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IDispatcher>)) return probe ? this : (object)(new global::IDispatcher[] { S2() });
			if (type == typeof(global::System.IServiceProvider)) return probe ? this : (object)(this);
			return null;
		}
		return null;
	}

	private global::System.IServiceProvider? Fallback => null;
	public object? GetService(global::System.Type serviceType) => GetKeyedService(serviceType, null);
	public object? GetKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, false) ?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);
	public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey) => GetKeyedService(serviceType, serviceKey) ?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");
	public T? GetService<T>() => this is HandlerProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;
	public T GetRequiredService<T>() => this is HandlerProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);
	global::IHandler<global::CancelOrder> HandlerProvider.IResolver<global::IHandler<global::CancelOrder>>.Get() => S0();
	global::IHandler<global::CreateOrder> HandlerProvider.IResolver<global::IHandler<global::CreateOrder>>.Get() => S1();
	global::IDispatcher HandlerProvider.IResolver<global::IDispatcher>.Get() => S2();
	global::System.Collections.Generic.IEnumerable<global::IHandler<global::CancelOrder>> HandlerProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::CancelOrder>>>.Get() => new global::IHandler<global::CancelOrder>[] { S0() };
	global::System.Collections.Generic.IEnumerable<global::IHandler<global::CreateOrder>> HandlerProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::CreateOrder>>>.Get() => new global::IHandler<global::CreateOrder>[] { S1() };
	global::System.Collections.Generic.IEnumerable<global::IDispatcher> HandlerProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IDispatcher>>.Get() => new global::IDispatcher[] { S2() };
	global::System.IServiceProvider HandlerProvider.IResolver<global::System.IServiceProvider>.Get() => this;
	private interface IResolver<T> { T Get(); }
	public bool IsService(global::System.Type serviceType) => IsKeyedService(serviceType, null);
	public bool IsKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, true) != null;
	public Scope CreateScope() => new Scope(this);

	private static T Required<T>(object? service) => service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");
	private T Track<T>(T service)
	{
		if (service is global::System.IDisposable) lock (_lock) (_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
		return service;
	}
	private object[] Drain() { lock (_lock) { var items = _disposables?.ToArray() ?? new object[0]; _disposables = null; global::System.Array.Reverse(items); return items; } }
	public void Dispose() { foreach (var item in Drain()) (item as global::System.IDisposable ?? throw new global::System.InvalidOperationException("'" + item.GetType() + "' only implements IAsyncDisposable, use DisposeAsync.")).Dispose(); }

	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public sealed class Scope : global::System.IServiceProvider, global::System.IDisposable, HandlerProvider.IResolver<global::IHandler<global::CancelOrder>>, HandlerProvider.IResolver<global::IHandler<global::CreateOrder>>, HandlerProvider.IResolver<global::IDispatcher>, HandlerProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::CancelOrder>>>, HandlerProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::CreateOrder>>>, HandlerProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IDispatcher>>, HandlerProvider.IResolver<global::System.IServiceProvider>
	{
		private readonly object _lock = new object();
		private global::System.Collections.Generic.List<object>? _disposables;
		private readonly HandlerProvider _root;
		public Scope(HandlerProvider root) => _root = root;
		public global::System.IServiceProvider ServiceProvider => this;

		private global::IHandler<global::CancelOrder> S0() => new global::CancelOrderHandler();
		private global::IHandler<global::CreateOrder> S1() => new global::CreateOrderHandler();
		private global::IDispatcher S2() => new global::Dispatcher(S1(), S0());

		private object? Resolve(global::System.Type type, object? key, bool probe)
		{
			if (key is null)
			{
				if (type == typeof(global::IHandler<global::CancelOrder>)) return probe ? this : (object)(S0());
				if (type == typeof(global::IHandler<global::CreateOrder>)) return probe ? this : (object)(S1());
				if (type == typeof(global::IDispatcher)) return probe ? this : (object)(S2());
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IHandler<global::CancelOrder>>)) return probe ? this : (object)(new global::IHandler<global::CancelOrder>[] { S0() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IHandler<global::CreateOrder>>)) return probe ? this : (object)(new global::IHandler<global::CreateOrder>[] { S1() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IDispatcher>)) return probe ? this : (object)(new global::IDispatcher[] { S2() });
				if (type == typeof(global::System.IServiceProvider)) return probe ? this : (object)(this);
				return null;
			}
			return null;
		}

		private global::System.IServiceProvider? Fallback => null;
		public object? GetService(global::System.Type serviceType) => GetKeyedService(serviceType, null);
		public object? GetKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, false) ?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);
		public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey) => GetKeyedService(serviceType, serviceKey) ?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");
		public T? GetService<T>() => this is HandlerProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;
		public T GetRequiredService<T>() => this is HandlerProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);
		global::IHandler<global::CancelOrder> HandlerProvider.IResolver<global::IHandler<global::CancelOrder>>.Get() => S0();
		global::IHandler<global::CreateOrder> HandlerProvider.IResolver<global::IHandler<global::CreateOrder>>.Get() => S1();
		global::IDispatcher HandlerProvider.IResolver<global::IDispatcher>.Get() => S2();
		global::System.Collections.Generic.IEnumerable<global::IHandler<global::CancelOrder>> HandlerProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::CancelOrder>>>.Get() => new global::IHandler<global::CancelOrder>[] { S0() };
		global::System.Collections.Generic.IEnumerable<global::IHandler<global::CreateOrder>> HandlerProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::CreateOrder>>>.Get() => new global::IHandler<global::CreateOrder>[] { S1() };
		global::System.Collections.Generic.IEnumerable<global::IDispatcher> HandlerProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IDispatcher>>.Get() => new global::IDispatcher[] { S2() };
		global::System.IServiceProvider HandlerProvider.IResolver<global::System.IServiceProvider>.Get() => this;
		public bool IsService(global::System.Type serviceType) => IsKeyedService(serviceType, null);
		public bool IsKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, true) != null;
		public Scope CreateScope() => new Scope(_root);

		private static T Required<T>(object? service) => service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");
		private T Track<T>(T service)
		{
			if (service is global::System.IDisposable) lock (_lock) (_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
			return service;
		}
		private object[] Drain() { lock (_lock) { var items = _disposables?.ToArray() ?? new object[0]; _disposables = null; global::System.Array.Reverse(items); return items; } }
		public void Dispose() { foreach (var item in Drain()) (item as global::System.IDisposable ?? throw new global::System.InvalidOperationException("'" + item.GetType() + "' only implements IAsyncDisposable, use DisposeAsync.")).Dispose(); }
	}
}
