//HintName: DependencyChainProvider.ServiceProvider.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

partial class DependencyChainProvider : global::System.IServiceProvider, global::System.IDisposable, DependencyChainProvider.IResolver<global::IChainA>, DependencyChainProvider.IResolver<global::IChainB>, DependencyChainProvider.IResolver<global::IChainC>, DependencyChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainA>>, DependencyChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainB>>, DependencyChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainC>>, DependencyChainProvider.IResolver<global::System.IServiceProvider>
{
	private readonly object _lock = new object();
	private global::System.Collections.Generic.List<object>? _disposables;

	private volatile global::IChainA? _S0;
	private global::IChainA S0() { var service = _S0; if (service is not null) return service; lock (_lock) return (_S0 ??= new global::ChainA(S1(), S2())); }
	private volatile global::IChainB? _S1;
	private global::IChainB S1() { var service = _S1; if (service is not null) return service; lock (_lock) return (_S1 ??= new global::ChainB(S2())); }
	private volatile global::IChainC? _S2;
	private global::IChainC S2() { var service = _S2; if (service is not null) return service; lock (_lock) return (_S2 ??= new global::ChainC()); }

	private object? Resolve(global::System.Type type, object? key, bool probe)
	{
		if (key is null)
		{
			if (type == typeof(global::IChainA)) return probe ? this : (object)(S0());
			if (type == typeof(global::IChainB)) return probe ? this : (object)(S1());
			if (type == typeof(global::IChainC)) return probe ? this : (object)(S2());
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IChainA>)) return probe ? this : (object)(new global::IChainA[] { S0() });
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IChainB>)) return probe ? this : (object)(new global::IChainB[] { S1() });
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IChainC>)) return probe ? this : (object)(new global::IChainC[] { S2() });
			if (type == typeof(global::System.IServiceProvider)) return probe ? this : (object)(this);
			return null;
		}
		return null;
	}

	private global::System.IServiceProvider? Fallback => null;
	public object? GetService(global::System.Type serviceType) => GetKeyedService(serviceType, null);
	public object? GetKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, false) ?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);
	public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey) => GetKeyedService(serviceType, serviceKey) ?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");
	public T? GetService<T>() => this is DependencyChainProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;
	public T GetRequiredService<T>() => this is DependencyChainProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);
	global::IChainA DependencyChainProvider.IResolver<global::IChainA>.Get() => S0();
	global::IChainB DependencyChainProvider.IResolver<global::IChainB>.Get() => S1();
	global::IChainC DependencyChainProvider.IResolver<global::IChainC>.Get() => S2();
	global::System.Collections.Generic.IEnumerable<global::IChainA> DependencyChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainA>>.Get() => new global::IChainA[] { S0() };
	global::System.Collections.Generic.IEnumerable<global::IChainB> DependencyChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainB>>.Get() => new global::IChainB[] { S1() };
	global::System.Collections.Generic.IEnumerable<global::IChainC> DependencyChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainC>>.Get() => new global::IChainC[] { S2() };
	global::System.IServiceProvider DependencyChainProvider.IResolver<global::System.IServiceProvider>.Get() => this;
	private interface IResolver<T> { T Get(); }
	public bool IsService(global::System.Type serviceType) => IsKeyedService(serviceType, null);
	public bool IsKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, true) != null;
	public Scope CreateScope() => new Scope(this);

	private static T Required<T>(object? service) => service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");
	private T Track<T>(T service)
	{
		if (service is global::System.IDisposable) lock (_lock) (_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
		return service;
	}
	private object[] Drain() { lock (_lock) { var items = _disposables?.ToArray() ?? new object[0]; _disposables = null; global::System.Array.Reverse(items); return items; } }
	public void Dispose() { foreach (var item in Drain()) (item as global::System.IDisposable ?? throw new global::System.InvalidOperationException("'" + item.GetType() + "' only implements IAsyncDisposable, use DisposeAsync.")).Dispose(); }

	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public sealed class Scope : global::System.IServiceProvider, global::System.IDisposable, DependencyChainProvider.IResolver<global::IChainA>, DependencyChainProvider.IResolver<global::IChainB>, DependencyChainProvider.IResolver<global::IChainC>, DependencyChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainA>>, DependencyChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainB>>, DependencyChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainC>>, DependencyChainProvider.IResolver<global::System.IServiceProvider>
	{
		private readonly object _lock = new object();
		private global::System.Collections.Generic.List<object>? _disposables;
		private readonly DependencyChainProvider _root;
		public Scope(DependencyChainProvider root) => _root = root;
		public global::System.IServiceProvider ServiceProvider => this;

		private global::IChainA S0() => _root.S0();
		private global::IChainB S1() => _root.S1();
		private global::IChainC S2() => _root.S2();

		private object? Resolve(global::System.Type type, object? key, bool probe)
		{
			if (key is null)
			{
				if (type == typeof(global::IChainA)) return probe ? this : (object)(S0());
				if (type == typeof(global::IChainB)) return probe ? this : (object)(S1());
				if (type == typeof(global::IChainC)) return probe ? this : (object)(S2());
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IChainA>)) return probe ? this : (object)(new global::IChainA[] { S0() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IChainB>)) return probe ? this : (object)(new global::IChainB[] { S1() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IChainC>)) return probe ? this : (object)(new global::IChainC[] { S2() });
				if (type == typeof(global::System.IServiceProvider)) return probe ? this : (object)(this);
				return null;
			}
			return null;
		}

		private global::System.IServiceProvider? Fallback => null;
		public object? GetService(global::System.Type serviceType) => GetKeyedService(serviceType, null);
		public object? GetKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, false) ?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);
		public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey) => GetKeyedService(serviceType, serviceKey) ?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");
		public T? GetService<T>() => this is DependencyChainProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;
		public T GetRequiredService<T>() => this is DependencyChainProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);
		global::IChainA DependencyChainProvider.IResolver<global::IChainA>.Get() => S0();
		global::IChainB DependencyChainProvider.IResolver<global::IChainB>.Get() => S1();
		global::IChainC DependencyChainProvider.IResolver<global::IChainC>.Get() => S2();
		global::System.Collections.Generic.IEnumerable<global::IChainA> DependencyChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainA>>.Get() => new global::IChainA[] { S0() };
		global::System.Collections.Generic.IEnumerable<global::IChainB> DependencyChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainB>>.Get() => new global::IChainB[] { S1() };
		global::System.Collections.Generic.IEnumerable<global::IChainC> DependencyChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainC>>.Get() => new global::IChainC[] { S2() };
		global::System.IServiceProvider DependencyChainProvider.IResolver<global::System.IServiceProvider>.Get() => this;
		public bool IsService(global::System.Type serviceType) => IsKeyedService(serviceType, null);
		public bool IsKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, true) != null;
		public Scope CreateScope() => new Scope(_root);

		private static T Required<T>(object? service) => service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");
		private T Track<T>(T service)
		{
			if (service is global::System.IDisposable) lock (_lock) (_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
			return service;
		}
		private object[] Drain() { lock (_lock) { var items = _disposables?.ToArray() ?? new object[0]; _disposables = null; global::System.Array.Reverse(items); return items; } }
		public void Dispose() { foreach (var item in Drain()) (item as global::System.IDisposable ?? throw new global::System.InvalidOperationException("'" + item.GetType() + "' only implements IAsyncDisposable, use DisposeAsync.")).Dispose(); }
	}
}
