//HintName: TransientChainProvider.ServiceProvider.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

partial class TransientChainProvider : global::System.IServiceProvider, global::System.IDisposable, TransientChainProvider.IResolver<global::IChainOuter>, TransientChainProvider.IResolver<global::IChainMiddle>, TransientChainProvider.IResolver<global::IChainInner>, TransientChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainOuter>>, TransientChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainMiddle>>, TransientChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainInner>>, TransientChainProvider.IResolver<global::System.IServiceProvider>
{
	private readonly object _lock = new object();
	private global::System.Collections.Generic.List<object>? _disposables;

	private global::IChainOuter S0() => new global::ChainOuter(S1(), S2());
	private global::IChainMiddle S1() => new global::ChainMiddle(S2());
	private global::IChainInner S2() => new global::ChainInner();

	private object? Resolve(global::System.Type type, object? key, bool probe)
	{
		if (key is null)
		{
			if (type == typeof(global::IChainOuter)) return probe ? this : (object)(S0());
			if (type == typeof(global::IChainMiddle)) return probe ? this : (object)(S1());
			if (type == typeof(global::IChainInner)) return probe ? this : (object)(S2());
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IChainOuter>)) return probe ? this : (object)(new global::IChainOuter[] { S0() });
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IChainMiddle>)) return probe ? this : (object)(new global::IChainMiddle[] { S1() });
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IChainInner>)) return probe ? this : (object)(new global::IChainInner[] { S2() });
			if (type == typeof(global::System.IServiceProvider)) return probe ? this : (object)(this);
			return null;
		}
		return null;
	}

	private global::System.IServiceProvider? Fallback => null;
	public object? GetService(global::System.Type serviceType) => GetKeyedService(serviceType, null);
	public object? GetKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, false) ?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);
	public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey) => GetKeyedService(serviceType, serviceKey) ?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");
	public T? GetService<T>() => this is TransientChainProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;
	public T GetRequiredService<T>() => this is TransientChainProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);
	global::IChainOuter TransientChainProvider.IResolver<global::IChainOuter>.Get() => S0();
	global::IChainMiddle TransientChainProvider.IResolver<global::IChainMiddle>.Get() => S1();
	global::IChainInner TransientChainProvider.IResolver<global::IChainInner>.Get() => S2();
	global::System.Collections.Generic.IEnumerable<global::IChainOuter> TransientChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainOuter>>.Get() => new global::IChainOuter[] { S0() };
	global::System.Collections.Generic.IEnumerable<global::IChainMiddle> TransientChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainMiddle>>.Get() => new global::IChainMiddle[] { S1() };
	global::System.Collections.Generic.IEnumerable<global::IChainInner> TransientChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainInner>>.Get() => new global::IChainInner[] { S2() };
	global::System.IServiceProvider TransientChainProvider.IResolver<global::System.IServiceProvider>.Get() => this;
	private interface IResolver<T> { T Get(); }
	public bool IsService(global::System.Type serviceType) => IsKeyedService(serviceType, null);
	public bool IsKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, true) != null;
	public Scope CreateScope() => new Scope(this);

	private static T Required<T>(object? service) => service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");
	private T Track<T>(T service)
	{
		if (service is global::System.IDisposable) lock (_lock) (_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
		return service;
	}
	private object[] Drain() { lock (_lock) { var items = _disposables?.ToArray() ?? new object[0]; _disposables = null; global::System.Array.Reverse(items); return items; } }
	public void Dispose() { foreach (var item in Drain()) (item as global::System.IDisposable ?? throw new global::System.InvalidOperationException("'" + item.GetType() + "' only implements IAsyncDisposable, use DisposeAsync.")).Dispose(); }

	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public sealed class Scope : global::System.IServiceProvider, global::System.IDisposable, TransientChainProvider.IResolver<global::IChainOuter>, TransientChainProvider.IResolver<global::IChainMiddle>, TransientChainProvider.IResolver<global::IChainInner>, TransientChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainOuter>>, TransientChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainMiddle>>, TransientChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainInner>>, TransientChainProvider.IResolver<global::System.IServiceProvider>
	{
		private readonly object _lock = new object();
		private global::System.Collections.Generic.List<object>? _disposables;
		private readonly TransientChainProvider _root;
		public Scope(TransientChainProvider root) => _root = root;
		public global::System.IServiceProvider ServiceProvider => this;

		private global::IChainOuter S0() => new global::ChainOuter(S1(), S2());
		private global::IChainMiddle S1() => new global::ChainMiddle(S2());
		private global::IChainInner S2() => new global::ChainInner();

		private object? Resolve(global::System.Type type, object? key, bool probe)
		{
			if (key is null)
			{
				if (type == typeof(global::IChainOuter)) return probe ? this : (object)(S0());
				if (type == typeof(global::IChainMiddle)) return probe ? this : (object)(S1());
				if (type == typeof(global::IChainInner)) return probe ? this : (object)(S2());
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IChainOuter>)) return probe ? this : (object)(new global::IChainOuter[] { S0() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IChainMiddle>)) return probe ? this : (object)(new global::IChainMiddle[] { S1() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IChainInner>)) return probe ? this : (object)(new global::IChainInner[] { S2() });
				if (type == typeof(global::System.IServiceProvider)) return probe ? this : (object)(this);
				return null;
			}
			return null;
		}

		private global::System.IServiceProvider? Fallback => null;
		public object? GetService(global::System.Type serviceType) => GetKeyedService(serviceType, null);
		public object? GetKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, false) ?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);
		public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey) => GetKeyedService(serviceType, serviceKey) ?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");
		public T? GetService<T>() => this is TransientChainProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;
		public T GetRequiredService<T>() => this is TransientChainProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);
		global::IChainOuter TransientChainProvider.IResolver<global::IChainOuter>.Get() => S0();
		global::IChainMiddle TransientChainProvider.IResolver<global::IChainMiddle>.Get() => S1();
		global::IChainInner TransientChainProvider.IResolver<global::IChainInner>.Get() => S2();
		global::System.Collections.Generic.IEnumerable<global::IChainOuter> TransientChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainOuter>>.Get() => new global::IChainOuter[] { S0() };
		global::System.Collections.Generic.IEnumerable<global::IChainMiddle> TransientChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainMiddle>>.Get() => new global::IChainMiddle[] { S1() };
		global::System.Collections.Generic.IEnumerable<global::IChainInner> TransientChainProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IChainInner>>.Get() => new global::IChainInner[] { S2() };
		global::System.IServiceProvider TransientChainProvider.IResolver<global::System.IServiceProvider>.Get() => this;
		public bool IsService(global::System.Type serviceType) => IsKeyedService(serviceType, null);
		public bool IsKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, true) != null;
		public Scope CreateScope() => new Scope(_root);

		private static T Required<T>(object? service) => service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");
		private T Track<T>(T service)
		{
			if (service is global::System.IDisposable) lock (_lock) (_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
			return service;
		}
		private object[] Drain() { lock (_lock) { var items = _disposables?.ToArray() ?? new object[0]; _disposables = null; global::System.Array.Reverse(items); return items; } }
		public void Dispose() { foreach (var item in Drain()) (item as global::System.IDisposable ?? throw new global::System.InvalidOperationException("'" + item.GetType() + "' only implements IAsyncDisposable, use DisposeAsync.")).Dispose(); }
	}
}
