//HintName: ConnectionProvider.ServiceProvider.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

partial class ConnectionProvider : 
	global::System.IServiceProvider,
	global::System.IDisposable,
	ConnectionProvider.IResolver<global::IClock>,
	ConnectionProvider.IResolver<global::IConnection>,
	ConnectionProvider.IResolver<global::IFormatter>,
	ConnectionProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IClock>>,
	ConnectionProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IConnection>>,
	ConnectionProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IFormatter>>,
	ConnectionProvider.IResolver<global::System.IServiceProvider>

{
	private readonly object _lock = new object();
	private global::System.Collections.Generic.List<object>? _disposables;

	private volatile global::IClock? _S0;
	private global::IClock S0()
	{
		var service = _S0;
		if (service is not null)
			return service;
		lock (_lock)
			return (_S0 ??= new global::Clock());
	}
	private global::IConnection S1() => Track<global::IConnection>(new global::Connection(S0()));
	private global::IFormatter S2() => new global::Formatter(S0());

	private object? Resolve(global::System.Type type, object? key, bool probe)
	{
		if (key is null)
		{
			if (type == typeof(global::IClock))
				return probe ? this : (object)(S0());
			if (type == typeof(global::IConnection))
				return probe ? this : (object)(S1());
			if (type == typeof(global::IFormatter))
				return probe ? this : (object)(S2());
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IClock>))
				return probe ? this : (object)(new global::IClock[] { S0() });
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IConnection>))
				return probe ? this : (object)(new global::IConnection[] { S1() });
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IFormatter>))
				return probe ? this : (object)(new global::IFormatter[] { S2() });
			if (type == typeof(global::System.IServiceProvider))
				return probe ? this : (object)(this);
			return null;
		}
		return null;
	}

	private global::System.IServiceProvider? Fallback => null;

	public object? GetService(global::System.Type serviceType)
		=> GetKeyedService(serviceType, null);

	public object? GetKeyedService(global::System.Type serviceType, object? serviceKey)
		=> Resolve(serviceType, serviceKey, false)
		?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);

	public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey)
		=> GetKeyedService(serviceType, serviceKey)
		?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");

	public T? GetService<T>()
		=> this is ConnectionProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;

	public T GetRequiredService<T>()
		=> this is ConnectionProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);

	private interface IResolver<T> { T Get(); }
	global::IClock ConnectionProvider.IResolver<global::IClock>.Get()
		=> S0();
	global::IConnection ConnectionProvider.IResolver<global::IConnection>.Get()
		=> S1();
	global::IFormatter ConnectionProvider.IResolver<global::IFormatter>.Get()
		=> S2();
	global::System.Collections.Generic.IEnumerable<global::IClock> ConnectionProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IClock>>.Get()
		=> new global::IClock[] { S0() };
	global::System.Collections.Generic.IEnumerable<global::IConnection> ConnectionProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IConnection>>.Get()
		=> new global::IConnection[] { S1() };
	global::System.Collections.Generic.IEnumerable<global::IFormatter> ConnectionProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IFormatter>>.Get()
		=> new global::IFormatter[] { S2() };
	global::System.IServiceProvider ConnectionProvider.IResolver<global::System.IServiceProvider>.Get()
		=> this;

	public bool IsService(global::System.Type serviceType)
		=> IsKeyedService(serviceType, null);

	public bool IsKeyedService(global::System.Type serviceType, object? serviceKey)
		=> Resolve(serviceType, serviceKey, true) != null;

	public Scope CreateScope() => new Scope(this);

	private static T Required<T>(object? service)
		=> service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");

	private T Track<T>(T service)
	{
		if (service is global::System.IDisposable)
			lock (_lock)
				(_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
		return service;
	}

	private object[] Drain()
	{
		lock (_lock)
		{
			var items = _disposables?.ToArray() ?? new object[0];
			_disposables = null;
			global::System.Array.Reverse(items);
			return items;
		}
	}

	public void Dispose()
	{
		foreach (var item in Drain())
		{
			if (item is global::System.IDisposable disposable)
			{
				disposable.Dispose();
			}
		}
	}

	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public sealed class Scope : 
		global::System.IServiceProvider,
		global::System.IDisposable,
		ConnectionProvider.IResolver<global::IClock>,
		ConnectionProvider.IResolver<global::IConnection>,
		ConnectionProvider.IResolver<global::IFormatter>,
		ConnectionProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IClock>>,
		ConnectionProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IConnection>>,
		ConnectionProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IFormatter>>,
		ConnectionProvider.IResolver<global::System.IServiceProvider>
	
	{
		private readonly object _lock = new object();
		private global::System.Collections.Generic.List<object>? _disposables;
		private readonly ConnectionProvider _root;
		public Scope(ConnectionProvider root) => _root = root;
		public global::System.IServiceProvider ServiceProvider => this;

		private global::IClock S0() => _root.S0();
		private global::IConnection S1() => Track<global::IConnection>(new global::Connection(S0()));
		private global::IFormatter S2() => new global::Formatter(S0());

		private object? Resolve(global::System.Type type, object? key, bool probe)
		{
			if (key is null)
			{
				if (type == typeof(global::IClock))
					return probe ? this : (object)(S0());
				if (type == typeof(global::IConnection))
					return probe ? this : (object)(S1());
				if (type == typeof(global::IFormatter))
					return probe ? this : (object)(S2());
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IClock>))
					return probe ? this : (object)(new global::IClock[] { S0() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IConnection>))
					return probe ? this : (object)(new global::IConnection[] { S1() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IFormatter>))
					return probe ? this : (object)(new global::IFormatter[] { S2() });
				if (type == typeof(global::System.IServiceProvider))
					return probe ? this : (object)(this);
				return null;
			}
			return null;
		}

		private global::System.IServiceProvider? Fallback => null;

		public object? GetService(global::System.Type serviceType)
			=> GetKeyedService(serviceType, null);

		public object? GetKeyedService(global::System.Type serviceType, object? serviceKey)
			=> Resolve(serviceType, serviceKey, false)
			?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);

		public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey)
			=> GetKeyedService(serviceType, serviceKey)
			?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");

		public T? GetService<T>()
			=> this is ConnectionProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;

		public T GetRequiredService<T>()
			=> this is ConnectionProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);

		global::IClock ConnectionProvider.IResolver<global::IClock>.Get()
			=> S0();
		global::IConnection ConnectionProvider.IResolver<global::IConnection>.Get()
			=> S1();
		global::IFormatter ConnectionProvider.IResolver<global::IFormatter>.Get()
			=> S2();
		global::System.Collections.Generic.IEnumerable<global::IClock> ConnectionProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IClock>>.Get()
			=> new global::IClock[] { S0() };
		global::System.Collections.Generic.IEnumerable<global::IConnection> ConnectionProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IConnection>>.Get()
			=> new global::IConnection[] { S1() };
		global::System.Collections.Generic.IEnumerable<global::IFormatter> ConnectionProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IFormatter>>.Get()
			=> new global::IFormatter[] { S2() };
		global::System.IServiceProvider ConnectionProvider.IResolver<global::System.IServiceProvider>.Get()
			=> this;

		public bool IsService(global::System.Type serviceType)
			=> IsKeyedService(serviceType, null);

		public bool IsKeyedService(global::System.Type serviceType, object? serviceKey)
			=> Resolve(serviceType, serviceKey, true) != null;

		public Scope CreateScope() => new Scope(_root);

		private static T Required<T>(object? service)
			=> service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");

		private T Track<T>(T service)
		{
			if (service is global::System.IDisposable)
				lock (_lock)
					(_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
			return service;
		}

		private object[] Drain()
		{
			lock (_lock)
			{
				var items = _disposables?.ToArray() ?? new object[0];
				_disposables = null;
				global::System.Array.Reverse(items);
				return items;
			}
		}

		public void Dispose()
		{
			foreach (var item in Drain())
			{
				if (item is global::System.IDisposable disposable)
				{
					disposable.Dispose();
				}
			}
		}
	}
}
