//HintName: TransientDependencyProvider.ServiceProvider.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

partial class TransientDependencyProvider : 
	global::System.IServiceProvider,
	global::System.IDisposable,
	TransientDependencyProvider.IResolver<global::ISharedConfig>,
	TransientDependencyProvider.IResolver<global::IRequestHandler>,
	TransientDependencyProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ISharedConfig>>,
	TransientDependencyProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IRequestHandler>>,
	TransientDependencyProvider.IResolver<global::System.IServiceProvider>

{
	private readonly object _lock = new object();
	private global::System.Collections.Generic.List<object>? _disposables;

	private volatile global::ISharedConfig? _S0;
	private global::ISharedConfig S0()
	{
		var service = _S0;
		if (service is not null)
			return service;
		lock (_lock)
			return (_S0 ??= new global::SharedConfig());
	}
	private global::IRequestHandler S1() => new global::RequestHandler(S0());

	private object? Resolve(global::System.Type type, object? key, bool probe)
	{
		if (key is null)
		{
			if (type == typeof(global::ISharedConfig))
				return probe ? this : (object)(S0());
			if (type == typeof(global::IRequestHandler))
				return probe ? this : (object)(S1());
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::ISharedConfig>))
				return probe ? this : (object)(new global::ISharedConfig[] { S0() });
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IRequestHandler>))
				return probe ? this : (object)(new global::IRequestHandler[] { S1() });
			if (type == typeof(global::System.IServiceProvider))
				return probe ? this : (object)(this);
			return null;
		}
		return null;
	}

	private global::System.IServiceProvider? Fallback => null;

	public object? GetService(global::System.Type serviceType)
		=> GetKeyedService(serviceType, null);

	public object? GetKeyedService(global::System.Type serviceType, object? serviceKey)
		=> Resolve(serviceType, serviceKey, false)
		?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);

	public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey)
		=> GetKeyedService(serviceType, serviceKey)
		?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");

	public T? GetService<T>()
		=> this is TransientDependencyProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;

	public T GetRequiredService<T>()
		=> this is TransientDependencyProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);

	private interface IResolver<T> { T Get(); }
	global::ISharedConfig TransientDependencyProvider.IResolver<global::ISharedConfig>.Get()
		=> S0();
	global::IRequestHandler TransientDependencyProvider.IResolver<global::IRequestHandler>.Get()
		=> S1();
	global::System.Collections.Generic.IEnumerable<global::ISharedConfig> TransientDependencyProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ISharedConfig>>.Get()
		=> new global::ISharedConfig[] { S0() };
	global::System.Collections.Generic.IEnumerable<global::IRequestHandler> TransientDependencyProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IRequestHandler>>.Get()
		=> new global::IRequestHandler[] { S1() };
	global::System.IServiceProvider TransientDependencyProvider.IResolver<global::System.IServiceProvider>.Get()
		=> this;

	public bool IsService(global::System.Type serviceType)
		=> IsKeyedService(serviceType, null);

	public bool IsKeyedService(global::System.Type serviceType, object? serviceKey)
		=> Resolve(serviceType, serviceKey, true) != null;

	public Scope CreateScope() => new Scope(this);

	private static T Required<T>(object? service)
		=> service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");

	private T Track<T>(T service)
	{
		if (service is global::System.IDisposable)
			lock (_lock)
				(_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
		return service;
	}

	private object[] Drain()
	{
		lock (_lock)
		{
			var items = _disposables?.ToArray() ?? new object[0];
			_disposables = null;
			global::System.Array.Reverse(items);
			return items;
		}
	}

	public void Dispose()
	{
		foreach (var item in Drain())
		{
			if (item is global::System.IDisposable disposable)
			{
				disposable.Dispose();
			}
		}
	}

	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public sealed class Scope : 
		global::System.IServiceProvider,
		global::System.IDisposable,
		TransientDependencyProvider.IResolver<global::ISharedConfig>,
		TransientDependencyProvider.IResolver<global::IRequestHandler>,
		TransientDependencyProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ISharedConfig>>,
		TransientDependencyProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IRequestHandler>>,
		TransientDependencyProvider.IResolver<global::System.IServiceProvider>
	
	{
		private readonly object _lock = new object();
		private global::System.Collections.Generic.List<object>? _disposables;
		private readonly TransientDependencyProvider _root;
		public Scope(TransientDependencyProvider root) => _root = root;
		public global::System.IServiceProvider ServiceProvider => this;

		private global::ISharedConfig S0() => _root.S0();
		private global::IRequestHandler S1() => new global::RequestHandler(S0());

		private object? Resolve(global::System.Type type, object? key, bool probe)
		{
			if (key is null)
			{
				if (type == typeof(global::ISharedConfig))
					return probe ? this : (object)(S0());
				if (type == typeof(global::IRequestHandler))
					return probe ? this : (object)(S1());
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::ISharedConfig>))
					return probe ? this : (object)(new global::ISharedConfig[] { S0() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IRequestHandler>))
					return probe ? this : (object)(new global::IRequestHandler[] { S1() });
				if (type == typeof(global::System.IServiceProvider))
					return probe ? this : (object)(this);
				return null;
			}
			return null;
		}

		private global::System.IServiceProvider? Fallback => null;

		public object? GetService(global::System.Type serviceType)
			=> GetKeyedService(serviceType, null);

		public object? GetKeyedService(global::System.Type serviceType, object? serviceKey)
			=> Resolve(serviceType, serviceKey, false)
			?? (serviceKey == null ? Fallback?.GetService(serviceType) : null);

		public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey)
			=> GetKeyedService(serviceType, serviceKey)
			?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");

		public T? GetService<T>()
			=> this is TransientDependencyProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;

		public T GetRequiredService<T>()
			=> this is TransientDependencyProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);

		global::ISharedConfig TransientDependencyProvider.IResolver<global::ISharedConfig>.Get()
			=> S0();
		global::IRequestHandler TransientDependencyProvider.IResolver<global::IRequestHandler>.Get()
			=> S1();
		global::System.Collections.Generic.IEnumerable<global::ISharedConfig> TransientDependencyProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ISharedConfig>>.Get()
			=> new global::ISharedConfig[] { S0() };
		global::System.Collections.Generic.IEnumerable<global::IRequestHandler> TransientDependencyProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IRequestHandler>>.Get()
			=> new global::IRequestHandler[] { S1() };
		global::System.IServiceProvider TransientDependencyProvider.IResolver<global::System.IServiceProvider>.Get()
			=> this;

		public bool IsService(global::System.Type serviceType)
			=> IsKeyedService(serviceType, null);

		public bool IsKeyedService(global::System.Type serviceType, object? serviceKey)
			=> Resolve(serviceType, serviceKey, true) != null;

		public Scope CreateScope() => new Scope(_root);

		private static T Required<T>(object? service)
			=> service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");

		private T Track<T>(T service)
		{
			if (service is global::System.IDisposable)
				lock (_lock)
					(_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
			return service;
		}

		private object[] Drain()
		{
			lock (_lock)
			{
				var items = _disposables?.ToArray() ?? new object[0];
				_disposables = null;
				global::System.Array.Reverse(items);
				return items;
			}
		}

		public void Dispose()
		{
			foreach (var item in Drain())
			{
				if (item is global::System.IDisposable disposable)
				{
					disposable.Dispose();
				}
			}
		}
	}
}
