//HintName: Guarded.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class Guarded
{
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public Guarded(global::IService service)
	{
		this._service = service ?? throw new global::System.ArgumentNullException("service");
	}
}
