//HintName: Inherited.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class Inherited
{
	[global::System.Runtime.CompilerServices.CompilerGenerated]
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	public Inherited(
		global::IAnotherService anotherService,
		global::IService service
	) : base(anotherService)
	{
		this._service = service;
	}
}
