//HintName: PostConstructWithDefaultParameter.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class PostConstructWithDefaultParameter
{
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public PostConstructWithDefaultParameter(global::Service service = default)
	{
		Initialize(service);
	}
}
