//HintName: PostConstructWithParameter.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class PostConstructWithParameter
{
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public PostConstructWithParameter(
		global::IService service,
		global::IInitializeService initialiseService
	)
	{
		this._service = service;
		Initialize(initialiseService);
	}
}
