//HintName: Properties.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class Properties
{
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public Properties(
		string getProperty,
		string protectedProperty,
		string initProperty,
		string requiredProperty
	)
	{
		this.GetProperty = getProperty;
		this.ProtectedProperty = protectedProperty;
		this.InitProperty = initProperty;
		this.RequiredProperty = requiredProperty;
	}
}
