//HintName: OrderContainer.ServiceProvider.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

partial class OrderContainer : 
	global::System.IServiceProvider,
	global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory,
	global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService,
	global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider,
	global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService,
	global::System.IDisposable,
	OrderContainer.IResolver<global::IHandler<global::CancelOrder>>,
	OrderContainer.IResolver<global::IHandler<global::CreateOrder>>,
	OrderContainer.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::CancelOrder>>>,
	OrderContainer.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::CreateOrder>>>,
	OrderContainer.IResolver<global::System.IServiceProvider>,
	OrderContainer.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory>,
	OrderContainer.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService>,
	OrderContainer.IResolver<global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider>,
	OrderContainer.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService>

{
	private readonly object _lock = new object();
	private global::System.Collections.Generic.List<object>? _disposables;

	private global::IHandler<global::CancelOrder> S0() => new global::CancelOrderHandler();
	private global::IHandler<global::CreateOrder> S1() => new global::CreateOrderHandler();

	private object? Resolve(global::System.Type type, object? key, bool probe)
	{
		if (key is null)
		{
			if (type == typeof(global::IHandler<global::CancelOrder>))
				return probe ? this : (object)(S0());
			if (type == typeof(global::IHandler<global::CreateOrder>))
				return probe ? this : (object)(S1());
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IHandler<global::CancelOrder>>))
				return probe ? this : (object)(new global::IHandler<global::CancelOrder>[] { S0() });
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IHandler<global::CreateOrder>>))
				return probe ? this : (object)(new global::IHandler<global::CreateOrder>[] { S1() });
			if (type == typeof(global::System.IServiceProvider))
				return probe ? this : (object)(this);
			if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory))
				return probe ? this : (object)(this);
			if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService))
				return probe ? this : (object)(this);
			if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider))
				return probe ? this : (object)(this);
			if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService))
				return probe ? this : (object)(this);
			return null;
		}
		return null;
	}

	private global::System.IServiceProvider? Fallback => null;

	public object? GetService(global::System.Type serviceType)
		=> GetKeyedService(serviceType, null);

	public object? GetKeyedService(global::System.Type serviceType, object? serviceKey)
		=> Resolve(serviceType, serviceKey, false)
		?? (serviceKey == null ? Fallback?.GetService(serviceType) : (Fallback as global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider)?.GetKeyedService(serviceType, serviceKey));

	public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey)
		=> GetKeyedService(serviceType, serviceKey)
		?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");

	public T? GetService<T>()
		=> this is OrderContainer.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;

	public T GetRequiredService<T>()
		=> this is OrderContainer.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);

	private interface IResolver<T> { T Get(); }
	global::IHandler<global::CancelOrder> OrderContainer.IResolver<global::IHandler<global::CancelOrder>>.Get()
		=> S0();
	global::IHandler<global::CreateOrder> OrderContainer.IResolver<global::IHandler<global::CreateOrder>>.Get()
		=> S1();
	global::System.Collections.Generic.IEnumerable<global::IHandler<global::CancelOrder>> OrderContainer.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::CancelOrder>>>.Get()
		=> new global::IHandler<global::CancelOrder>[] { S0() };
	global::System.Collections.Generic.IEnumerable<global::IHandler<global::CreateOrder>> OrderContainer.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::CreateOrder>>>.Get()
		=> new global::IHandler<global::CreateOrder>[] { S1() };
	global::System.IServiceProvider OrderContainer.IResolver<global::System.IServiceProvider>.Get()
		=> this;
	global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory OrderContainer.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory>.Get()
		=> this;
	global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService OrderContainer.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService>.Get()
		=> this;
	global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider OrderContainer.IResolver<global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider>.Get()
		=> this;
	global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService OrderContainer.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService>.Get()
		=> this;

	public bool IsService(global::System.Type serviceType)
		=> IsKeyedService(serviceType, null);

	public bool IsKeyedService(global::System.Type serviceType, object? serviceKey)
		=> Resolve(serviceType, serviceKey, true) != null || (serviceKey == null ? Fallback is global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService s && s.IsService(serviceType) : Fallback is global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService k && k.IsKeyedService(serviceType, serviceKey));

	public Scope CreateScope() => new Scope(this);
	global::Microsoft.Extensions.DependencyInjection.IServiceScope global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory.CreateScope() => CreateScope();

	private static T Required<T>(object? service)
		=> service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");

	private T Track<T>(T service)
	{
		if (service is global::System.IDisposable)
			lock (_lock)
				(_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
		return service;
	}

	private object[] Drain()
	{
		lock (_lock)
		{
			var items = _disposables?.ToArray() ?? new object[0];
			_disposables = null;
			global::System.Array.Reverse(items);
			return items;
		}
	}

	public void Dispose()
	{
		foreach (var item in Drain())
		{
			if (item is global::System.IDisposable disposable)
			{
				disposable.Dispose();
			}
		}
	}

	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public sealed class Scope : 
		global::System.IServiceProvider,
		global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory,
		global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService,
		global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider,
		global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService,
		global::System.IDisposable,
		global::Microsoft.Extensions.DependencyInjection.IServiceScope,
		OrderContainer.IResolver<global::IHandler<global::CancelOrder>>,
		OrderContainer.IResolver<global::IHandler<global::CreateOrder>>,
		OrderContainer.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::CancelOrder>>>,
		OrderContainer.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::CreateOrder>>>,
		OrderContainer.IResolver<global::System.IServiceProvider>,
		OrderContainer.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory>,
		OrderContainer.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService>,
		OrderContainer.IResolver<global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider>,
		OrderContainer.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService>
	
	{
		private readonly object _lock = new object();
		private global::System.Collections.Generic.List<object>? _disposables;
		private readonly OrderContainer _root;
		public Scope(OrderContainer root) => _root = root;
		public global::System.IServiceProvider ServiceProvider => this;

		private global::IHandler<global::CancelOrder> S0() => new global::CancelOrderHandler();
		private global::IHandler<global::CreateOrder> S1() => new global::CreateOrderHandler();

		private object? Resolve(global::System.Type type, object? key, bool probe)
		{
			if (key is null)
			{
				if (type == typeof(global::IHandler<global::CancelOrder>))
					return probe ? this : (object)(S0());
				if (type == typeof(global::IHandler<global::CreateOrder>))
					return probe ? this : (object)(S1());
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IHandler<global::CancelOrder>>))
					return probe ? this : (object)(new global::IHandler<global::CancelOrder>[] { S0() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IHandler<global::CreateOrder>>))
					return probe ? this : (object)(new global::IHandler<global::CreateOrder>[] { S1() });
				if (type == typeof(global::System.IServiceProvider))
					return probe ? this : (object)(this);
				if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory))
					return probe ? this : (object)(this);
				if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService))
					return probe ? this : (object)(this);
				if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider))
					return probe ? this : (object)(this);
				if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService))
					return probe ? this : (object)(this);
				return null;
			}
			return null;
		}

		private global::System.IServiceProvider? Fallback => null;

		public object? GetService(global::System.Type serviceType)
			=> GetKeyedService(serviceType, null);

		public object? GetKeyedService(global::System.Type serviceType, object? serviceKey)
			=> Resolve(serviceType, serviceKey, false)
			?? (serviceKey == null ? Fallback?.GetService(serviceType) : (Fallback as global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider)?.GetKeyedService(serviceType, serviceKey));

		public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey)
			=> GetKeyedService(serviceType, serviceKey)
			?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");

		public T? GetService<T>()
			=> this is OrderContainer.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;

		public T GetRequiredService<T>()
			=> this is OrderContainer.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);

		global::IHandler<global::CancelOrder> OrderContainer.IResolver<global::IHandler<global::CancelOrder>>.Get()
			=> S0();
		global::IHandler<global::CreateOrder> OrderContainer.IResolver<global::IHandler<global::CreateOrder>>.Get()
			=> S1();
		global::System.Collections.Generic.IEnumerable<global::IHandler<global::CancelOrder>> OrderContainer.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::CancelOrder>>>.Get()
			=> new global::IHandler<global::CancelOrder>[] { S0() };
		global::System.Collections.Generic.IEnumerable<global::IHandler<global::CreateOrder>> OrderContainer.IResolver<global::System.Collections.Generic.IEnumerable<global::IHandler<global::CreateOrder>>>.Get()
			=> new global::IHandler<global::CreateOrder>[] { S1() };
		global::System.IServiceProvider OrderContainer.IResolver<global::System.IServiceProvider>.Get()
			=> this;
		global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory OrderContainer.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory>.Get()
			=> this;
		global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService OrderContainer.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService>.Get()
			=> this;
		global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider OrderContainer.IResolver<global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider>.Get()
			=> this;
		global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService OrderContainer.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService>.Get()
			=> this;

		public bool IsService(global::System.Type serviceType)
			=> IsKeyedService(serviceType, null);

		public bool IsKeyedService(global::System.Type serviceType, object? serviceKey)
			=> Resolve(serviceType, serviceKey, true) != null || (serviceKey == null ? Fallback is global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService s && s.IsService(serviceType) : Fallback is global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService k && k.IsKeyedService(serviceType, serviceKey));

		public Scope CreateScope() => new Scope(_root);
		global::Microsoft.Extensions.DependencyInjection.IServiceScope global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory.CreateScope() => CreateScope();

		private static T Required<T>(object? service)
			=> service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");

		private T Track<T>(T service)
		{
			if (service is global::System.IDisposable)
				lock (_lock)
					(_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
			return service;
		}

		private object[] Drain()
		{
			lock (_lock)
			{
				var items = _disposables?.ToArray() ?? new object[0];
				_disposables = null;
				global::System.Array.Reverse(items);
				return items;
			}
		}

		public void Dispose()
		{
			foreach (var item in Drain())
			{
				if (item is global::System.IDisposable disposable)
				{
					disposable.Dispose();
				}
			}
		}
	}
}
