using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

internal static class ModelUtilities
{
    public static string? GetServiceKey(ISymbol symbol)
    {
        var keyedService = symbol.GetAttributes()
            .Where(a => a.AttributeClass?.ToDisplayString() == AttributeNames.AutoKeyedService
                || a.AttributeClass?.ToDisplayString() == "Microsoft.Extensions.DependencyInjection.FromKeyedServicesAttribute")
            .FirstOrDefault();

        if (keyedService != null)
            return keyedService.ConstructorArguments[0].ToCSharpString();

        return null;
    }

    public static bool HasIgnoreAttribute(IEnumerable<AttributeData> attributes) =>
        attributes.Any(static a => a.AttributeClass?.ToDisplayString()
        == AttributeNames.AutoConstructIgnore);

    public static bool IsValidField(IFieldSymbol field)
    {
        if (!field.IsReadOnly || field.IsStatic || !field.CanBeReferencedByName || field.IsImplicitlyDeclared)
            return false;

        // compiler-generated backing field
        if (field.AssociatedSymbol is not null)
            return false;

        if (HasIgnoreAttribute(field.GetAttributes()))
            return false;

        if (field.DeclaringSyntaxReferences
            .Select(x => x.GetSyntax())
            .OfType<VariableDeclaratorSyntax>()
            .Any(x => x.Initializer != null))
            return false;

        return true;
    }

    public static bool IsValidProperty(IPropertySymbol property)
    {
        if (property.IsStatic || !property.CanBeReferencedByName || property.IsImplicitlyDeclared)
            return false;

        if (HasIgnoreAttribute(property.GetAttributes()))
            return false;

        // Property has a backing field generated by the compiler
        if (!property.ContainingType.GetMembers().OfType<IFieldSymbol>()
            .Any(field => SymbolEqualityComparer.Default.Equals(field.AssociatedSymbol, property)))
            return false;

        var propertySyntax = property.DeclaringSyntaxReferences
            .Select(x => x.GetSyntax())
            .OfType<PropertyDeclarationSyntax>()
            .FirstOrDefault();
        if (propertySyntax is null)
            return false;

        // Expression Body Definitions
        // https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/properties#expression-body-definitions
        if (property.IsReadOnly && propertySyntax.AccessorList is null)
            return false;

        // Property has a getter with a body only
        if (property.IsReadOnly
            && propertySyntax.AccessorList?.Accessors.Count == 1
            && propertySyntax.AccessorList.Accessors[0].IsKind(SyntaxKind.GetAccessorDeclaration)
            && propertySyntax.AccessorList.Accessors[0].Body is not null)
            return false;

        if (propertySyntax.Initializer is not null)
            return false;

        // Not required and not init properties
        if (!property.IsReadOnly
#if ROSLYN_4_4
            && !property.IsRequired
#endif
            // init
            && propertySyntax.AccessorList?.Accessors
            .Any(static a => a.IsKind(SyntaxKind.InitAccessorDeclaration)) != true)
            return false;

        return true;
    }
}
