using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

internal static class Utilities
{
    // These run once per member of every [AutoConstruct] type, so they loop directly over
    // the ImmutableArrays: LINQ here boxed the array and allocated iterators per member.

    public static string? GetServiceKey(ISymbol symbol)
    {
        foreach (var attribute in symbol.GetAttributes())
        {
            var name = attribute.AttributeClass?.ToDisplayString();
            if (name == AttributeNames.AutoKeyedService
                || name == "Microsoft.Extensions.DependencyInjection.FromKeyedServicesAttribute")
                return attribute.ConstructorArguments[0].ToCSharpString();
        }

        return null;
    }

    public static bool HasIgnoreAttribute(ImmutableArray<AttributeData> attributes)
    {
        foreach (var attribute in attributes)
        {
            if (attribute.AttributeClass?.ToDisplayString() == AttributeNames.AutoConstructIgnore)
                return true;
        }
        return false;
    }

    public static bool IsValidField(IFieldSymbol field)
    {
        if (!field.IsReadOnly || field.IsStatic || !field.CanBeReferencedByName || field.IsImplicitlyDeclared)
            return false;

        // compiler-generated backing field
        if (field.AssociatedSymbol is not null)
            return false;

        if (HasIgnoreAttribute(field.GetAttributes()))
            return false;

        foreach (var reference in field.DeclaringSyntaxReferences)
        {
            if (reference.GetSyntax() is VariableDeclaratorSyntax { Initializer: not null })
                return false;
        }

        return true;
    }

    public static bool IsValidProperty(IPropertySymbol property)
    {
        if (property.IsStatic || !property.CanBeReferencedByName || property.IsImplicitlyDeclared)
            return false;

        if (HasIgnoreAttribute(property.GetAttributes()))
            return false;

        // Property has a backing field generated by the compiler
        if (!HasBackingField(property))
            return false;

        PropertyDeclarationSyntax? propertySyntax = null;
        foreach (var reference in property.DeclaringSyntaxReferences)
        {
            if (reference.GetSyntax() is PropertyDeclarationSyntax syntax)
            {
                propertySyntax = syntax;
                break;
            }
        }
        if (propertySyntax is null)
            return false;

        // Expression Body Definitions
        // https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/properties#expression-body-definitions
        if (property.IsReadOnly && propertySyntax.AccessorList is null)
            return false;

        // Property has a getter with a body only
        if (property.IsReadOnly
            && propertySyntax.AccessorList?.Accessors.Count == 1
            && propertySyntax.AccessorList.Accessors[0].IsKind(SyntaxKind.GetAccessorDeclaration)
            && propertySyntax.AccessorList.Accessors[0].Body is not null)
            return false;

        if (propertySyntax.Initializer is not null)
            return false;

        // Not required and not init properties
        if (!property.IsReadOnly
#if ROSLYN_4_4
            && !property.IsRequired
#endif
            // init
            && propertySyntax.AccessorList?.Accessors
            .Any(static a => a.IsKind(SyntaxKind.InitAccessorDeclaration)) != true)
            return false;

        return true;
    }

    // ponytail: scans every member per property, so O(members x properties); precompute the
    // set of backing fields per type if property-heavy types ever show up in a profile.
    private static bool HasBackingField(IPropertySymbol property)
    {
        foreach (var member in property.ContainingType.GetMembers())
        {
            if (member is IFieldSymbol field
                && SymbolEqualityComparer.Default.Equals(field.AssociatedSymbol, property))
                return true;
        }
        return false;
    }

    public static bool HasEligibleMember(INamedTypeSymbol type)
    {
        foreach (var member in type.GetMembers())
        {
            if (member is IFieldSymbol field && IsValidField(field))
                return true;

            if (member is IPropertySymbol property && IsValidProperty(property))
                return true;
        }
        return false;
    }

    public static IEnumerable<ISymbol> GetEligibleMembers(INamedTypeSymbol type)
    {
        foreach (var member in type.GetMembers())
        {
            if (member is IFieldSymbol field && IsValidField(field))
                yield return member;

            if (member is IPropertySymbol property && IsValidProperty(property))
                yield return member;
        }
    }

    public static bool HasAttribute(ISymbol? symbol, string attributeName)
    {
        return symbol != null && symbol.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == attributeName);
    }

    public static bool IsAutoConstructInCompilation(Compilation compilation)
    {
        return compilation.GetTypeByMetadataName(AttributeNames.AutoConstruct) is not null;
    }
}
