public interface IExampleA { }
public interface IExampleB { }
public interface IExampleC { }
public interface IExampleD { }
public interface IExampleE { }
public interface IExampleF { }
public interface IExampleG { }
public interface IExampleH { }
public interface IExampleI { }
public interface IExampleJ { }
public interface IExampleK { }
public interface IExampleL { }
public interface IExampleM { }
public interface IExampleN { }
public interface IExampleO { }
public interface IExampleP { }
public interface IExampleQ { }
public interface IExampleR { }
public interface IExampleS { }
public interface IExampleT { }
public interface IExampleU { }
public interface IExampleV { }
public interface IExampleW { }
public interface IExampleX { }
public interface IExampleY { }
public interface IExampleZ { }

public interface IA { }
public interface IB { }
public interface IC { }
public interface ID { }
public interface IE { }
public interface IF { }
public interface IG { }
public interface IH { }
public interface II { }
public interface IJ { }
public interface IK { }
public interface IL { }
public interface IM { }
public interface IN { }
public interface IO { }
public interface IP { }
public interface IQ { }
public interface IR { }
public interface IS { }
public interface IT { }
public interface IU { }
public interface IV { }
public interface IW { }
public interface IX { }
public interface IY { }
public interface IZ { }
