//HintName: AllParametersAreSameTypeTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class AllParametersAreSameTypeTest
{
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public AllParametersAreSameTypeTest(global::IService baseService, global::IService service) : base(baseService)
	{
		this._service = service;
		Initialize(service);
	}
}
