//HintName: CClass.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class CClass
{
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public CClass(
		global::IServiceA service,
		global::IServiceB service0,
		global::IServiceC service1
	) : base(service, service0)
	{
		this._service = service1;
	}
}
