//HintName: ExcludeStaticAndInitialisedFieldsTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class ExcludeStaticAndInitialisedFieldsTest
{
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public ExcludeStaticAndInitialisedFieldsTest(int s)
	{
		this._s = s;
	}
}
