//HintName: ConcreteClassWithAnotherField.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class ConcreteClassWithAnotherField
{
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public ConcreteClassWithAnotherField(global::IServiceA t, global::IServiceB serviceb) : base(t)
	{
		this._serviceb = serviceb;
	}
}
