//HintName: ConcreteClass1[T].g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class ConcreteClass1<T>
{
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public ConcreteClass1(global::IServiceA t1, T t2) : base(t1, t2)
	{
	}
}
