//HintName: B.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class B
{
	[global::System.Runtime.CompilerServices.CompilerGenerated]
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	public B(
		global::IServiceE serviceE,
		global::IServiceD serviceD,
		global::IServiceC serviceC,
		global::IServiceB serviceB
	) : base(serviceE, serviceD, serviceC)
	{
		this._serviceB = serviceB;
	}
}
