//HintName: C.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class C
{
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public C(
		global::IServiceE serviceE,
		global::IServiceD serviceD,
		global::IServiceC serviceC
	) : base(serviceE, serviceD)
	{
		this._serviceC = serviceC;
	}
}
