//HintName: A.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class A
{
	[global::System.Runtime.CompilerServices.CompilerGenerated]
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Generated code.")]
	public A(
		global::IServiceE serviceE,
		global::IServiceD serviceD,
		global::IServiceC serviceC,
		global::IServiceB serviceB,
		global::IServiceA serviceA
	) : base(serviceE, serviceD, serviceC, serviceB)
	{
		this._serviceA = serviceA;
	}
}
