//HintName: IInterface.NestedClass.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial interface IInterface
{
	partial class NestedClass
	{
		[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
		public NestedClass(global::IInterface item)
		{
			this.Item = item;
		}
	}
}
