//HintName: TestNamespace.NamespaceTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestNamespace
{
	partial class NamespaceTest
	{
		[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
		public NamespaceTest(int item)
		{
			this._item = item;
		}
	}
}
