//HintName: TestNamespace.OuterClass1.OuterClass2.NamespaceDoubleNestedClassTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestNamespace
{
	partial class OuterClass1
	{
		partial class OuterClass2
		{
			partial class NamespaceDoubleNestedClassTest
			{
				[global::System.Runtime.CompilerServices.CompilerGenerated]
				[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
				[global::System.Diagnostics.DebuggerNonUserCode]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Generated code.")]
				public NamespaceDoubleNestedClassTest(int item)
				{
					this._item = item;
				}
			}
		}
	}
}
