//HintName: OuterClass.NestedClassTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class OuterClass
{
	partial class NestedClassTest
	{
		[global::System.Runtime.CompilerServices.CompilerGenerated]
		[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
		[global::System.Diagnostics.DebuggerNonUserCode]
		[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
		public NestedClassTest(int item)
		{
			this._item = item;
		}
	}
}
