//HintName: PostCtorWithOptionalArgumentsTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class PostCtorWithOptionalArgumentsTest
{
	[global::System.Runtime.CompilerServices.CompilerGenerated]
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Generated code.")]
	public PostCtorWithOptionalArgumentsTest(
		global::IServiceA serviceA,
		global::IServiceB serviceB = default
	)
	{
		this._serviceA = serviceA;
		Initialize(serviceB);
	}
}
