//HintName: PostCtorWithOutArgumentTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class PostCtorWithOutArgumentTest
{
	[global::System.Runtime.CompilerServices.CompilerGenerated]
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Generated code.")]
	public PostCtorWithOutArgumentTest(
		global::IServiceA serviceA,
		global::IServiceFactory serviceFactory
	)
	{
		this._serviceA = serviceA;
		Initialize(serviceFactory, out this._serviceB);
	}
}
