//HintName: PostCtorWithRefReadonlyArgumentTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class PostCtorWithRefReadonlyArgumentTest
{
	[global::System.Runtime.CompilerServices.CompilerGenerated]
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Generated code.")]
	public PostCtorWithRefReadonlyArgumentTest(
		global::IServiceA serviceA,
		global::IServiceB serviceB,
		global::IServiceFactory serviceFactory
	)
	{
		this._serviceA = serviceA;
		this._serviceB = serviceB;
		Initialize(serviceFactory, in serviceB);
	}
}
