//HintName: PostCtorOptionalDefault.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class PostCtorOptionalDefault
{
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public PostCtorOptionalDefault(string value = default, global::Flag flag = (global::Flag)0)
	{
		Initialize(value, flag);
	}
}
