//HintName: PostCtorWithArgumentsTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class PostCtorWithArgumentsTest
{
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public PostCtorWithArgumentsTest(global::IServiceA a, global::IServiceB b)
	{
		this.a = a;
		Initialize(b);
	}
}
