//HintName: BaseClass.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class BaseClass
{
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public BaseClass(
		[global::Microsoft.Extensions.DependencyInjection.FromKeyedServices("base")] global::IService service
	)
	{
		this._service = service;
	}
}
