//HintName: PostCtorWithKeyedServiceOutParameterTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class PostCtorWithKeyedServiceOutParameterTest
{
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public PostCtorWithKeyedServiceOutParameterTest()
	{
		Initialize(out this._service);
	}
}
