//HintName: PostCtorWithInArgumentTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class PostCtorWithInArgumentTest
{
	[global::System.Runtime.CompilerServices.CompilerGenerated]
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	public PostCtorWithInArgumentTest(
		global::IServiceA serviceA,
		global::IServiceB serviceB,
		global::IServiceFactory serviceFactory
	)
	{
		this._serviceA = serviceA;
		this._serviceB = serviceB;
		Initialize(serviceFactory, in serviceB);
	}
}
