//HintName: UniqueNameTest.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class UniqueNameTest
{
	[global::System.Runtime.CompilerServices.CompilerGenerated]
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	public UniqueNameTest(
		global::IServiceC serviceC,
		global::IServiceA serviceA,
		global::IServiceB serviceB
	) : base(serviceC)
	{
		this._serviceA = serviceA;
		Initialize(serviceB);
	}
}
