//HintName: UniqueNameTest2.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class UniqueNameTest2
{
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public UniqueNameTest2(int value) : base(value)
	{
		this._value = value;
		this.value = value;
		Initialise(value);
	}
}
