//HintName: UniqueNameTestBase.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

partial class UniqueNameTestBase
{
	[global::System.Runtime.CompilerServices.CompilerGenerated]
	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Generated code.")]
	public UniqueNameTestBase(int value)
	{
		this._value = value;
		this.value = value;
		Initialise(value);
	}
}
