//HintName: DisposableProvider.ServiceProvider.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/AutoCtor
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

partial class DisposableProvider : global::System.IServiceProvider, global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory, global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService, global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider, global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService, global::System.IDisposable, DisposableProvider.IResolver<global::IPoolOwner>, DisposableProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IPoolOwner>>, DisposableProvider.IResolver<global::System.IServiceProvider>, DisposableProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory>, DisposableProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService>, DisposableProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider>, DisposableProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService>
{
	private readonly object _lock = new object();
	private global::System.Collections.Generic.List<object>? _disposables;

	private volatile global::IPoolOwner? _S0;
	private global::IPoolOwner S0() { var service = _S0; if (service is not null) return service; lock (_lock) return (_S0 ??= Track<global::IPoolOwner>(new global::PoolOwner())); }

	private object? Resolve(global::System.Type type, object? key, bool probe)
	{
		if (key is null)
		{
			if (type == typeof(global::IPoolOwner)) return probe ? this : (object)(S0());
			if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IPoolOwner>)) return probe ? this : (object)(new global::IPoolOwner[] { S0() });
			if (type == typeof(global::System.IServiceProvider)) return probe ? this : (object)(this);
			if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory)) return probe ? this : (object)(this);
			if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService)) return probe ? this : (object)(this);
			if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider)) return probe ? this : (object)(this);
			if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService)) return probe ? this : (object)(this);
			return null;
		}
		return null;
	}

	private global::System.IServiceProvider? Fallback => null;
	public object? GetService(global::System.Type serviceType) => GetKeyedService(serviceType, null);
	public object? GetKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, false) ?? (serviceKey == null ? Fallback?.GetService(serviceType) : (Fallback as global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider)?.GetKeyedService(serviceType, serviceKey));
	public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey) => GetKeyedService(serviceType, serviceKey) ?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");
	public T? GetService<T>() => this is DisposableProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;
	public T GetRequiredService<T>() => this is DisposableProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);
	global::IPoolOwner DisposableProvider.IResolver<global::IPoolOwner>.Get() => S0();
	global::System.Collections.Generic.IEnumerable<global::IPoolOwner> DisposableProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IPoolOwner>>.Get() => new global::IPoolOwner[] { S0() };
	global::System.IServiceProvider DisposableProvider.IResolver<global::System.IServiceProvider>.Get() => this;
	global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory DisposableProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory>.Get() => this;
	global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService DisposableProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService>.Get() => this;
	global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider DisposableProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider>.Get() => this;
	global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService DisposableProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService>.Get() => this;
	private interface IResolver<T> { T Get(); }
	public bool IsService(global::System.Type serviceType) => IsKeyedService(serviceType, null);
	public bool IsKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, true) != null || (serviceKey == null ? Fallback is global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService s && s.IsService(serviceType) : Fallback is global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService k && k.IsKeyedService(serviceType, serviceKey));
	public Scope CreateScope() => new Scope(this);
	global::Microsoft.Extensions.DependencyInjection.IServiceScope global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory.CreateScope() => CreateScope();

	private static T Required<T>(object? service) => service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");
	private T Track<T>(T service)
	{
		if (service is global::System.IDisposable) lock (_lock) (_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
		return service;
	}
	private object[] Drain() { lock (_lock) { var items = _disposables?.ToArray() ?? new object[0]; _disposables = null; global::System.Array.Reverse(items); return items; } }
	public void Dispose() { foreach (var item in Drain()) (item as global::System.IDisposable ?? throw new global::System.InvalidOperationException("'" + item.GetType() + "' only implements IAsyncDisposable, use DisposeAsync.")).Dispose(); }

	[global::System.CodeDom.Compiler.GeneratedCode("AutoCtor", "0.0.0.0")]
	public sealed class Scope : global::System.IServiceProvider, global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory, global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService, global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider, global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService, global::System.IDisposable, global::Microsoft.Extensions.DependencyInjection.IServiceScope, DisposableProvider.IResolver<global::IPoolOwner>, DisposableProvider.IResolver<global::ISession>, DisposableProvider.IResolver<global::ITracker>, DisposableProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IPoolOwner>>, DisposableProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ISession>>, DisposableProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ITracker>>, DisposableProvider.IResolver<global::System.IServiceProvider>, DisposableProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory>, DisposableProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService>, DisposableProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider>, DisposableProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService>
	{
		private readonly object _lock = new object();
		private global::System.Collections.Generic.List<object>? _disposables;
		private readonly DisposableProvider _root;
		public Scope(DisposableProvider root) => _root = root;
		public global::System.IServiceProvider ServiceProvider => this;

		private global::IPoolOwner S0() => _root.S0();
		private volatile global::ISession? _S1;
		private global::ISession S1() { var service = _S1; if (service is not null) return service; lock (_lock) return (_S1 ??= Track<global::ISession>(new global::Session(S0()))); }
		private volatile global::ITracker? _S2;
		private global::ITracker S2() { var service = _S2; if (service is not null) return service; lock (_lock) return (_S2 ??= new global::Tracker(S1())); }

		private object? Resolve(global::System.Type type, object? key, bool probe)
		{
			if (key is null)
			{
				if (type == typeof(global::IPoolOwner)) return probe ? this : (object)(S0());
				if (type == typeof(global::ISession)) return probe ? this : (object)(S1());
				if (type == typeof(global::ITracker)) return probe ? this : (object)(S2());
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::IPoolOwner>)) return probe ? this : (object)(new global::IPoolOwner[] { S0() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::ISession>)) return probe ? this : (object)(new global::ISession[] { S1() });
				if (type == typeof(global::System.Collections.Generic.IEnumerable<global::ITracker>)) return probe ? this : (object)(new global::ITracker[] { S2() });
				if (type == typeof(global::System.IServiceProvider)) return probe ? this : (object)(this);
				if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory)) return probe ? this : (object)(this);
				if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService)) return probe ? this : (object)(this);
				if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider)) return probe ? this : (object)(this);
				if (type == typeof(global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService)) return probe ? this : (object)(this);
				return null;
			}
			return null;
		}

		private global::System.IServiceProvider? Fallback => null;
		public object? GetService(global::System.Type serviceType) => GetKeyedService(serviceType, null);
		public object? GetKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, false) ?? (serviceKey == null ? Fallback?.GetService(serviceType) : (Fallback as global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider)?.GetKeyedService(serviceType, serviceKey));
		public object GetRequiredKeyedService(global::System.Type serviceType, object? serviceKey) => GetKeyedService(serviceType, serviceKey) ?? throw new global::System.InvalidOperationException("No service for type '" + serviceType + "' has been registered.");
		public T? GetService<T>() => this is DisposableProvider.IResolver<T> resolver ? resolver.Get() : GetService(typeof(T)) is T service ? service : default;
		public T GetRequiredService<T>() => this is DisposableProvider.IResolver<T> resolver ? resolver.Get() : (T)GetRequiredKeyedService(typeof(T), null);
		global::IPoolOwner DisposableProvider.IResolver<global::IPoolOwner>.Get() => S0();
		global::ISession DisposableProvider.IResolver<global::ISession>.Get() => S1();
		global::ITracker DisposableProvider.IResolver<global::ITracker>.Get() => S2();
		global::System.Collections.Generic.IEnumerable<global::IPoolOwner> DisposableProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::IPoolOwner>>.Get() => new global::IPoolOwner[] { S0() };
		global::System.Collections.Generic.IEnumerable<global::ISession> DisposableProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ISession>>.Get() => new global::ISession[] { S1() };
		global::System.Collections.Generic.IEnumerable<global::ITracker> DisposableProvider.IResolver<global::System.Collections.Generic.IEnumerable<global::ITracker>>.Get() => new global::ITracker[] { S2() };
		global::System.IServiceProvider DisposableProvider.IResolver<global::System.IServiceProvider>.Get() => this;
		global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory DisposableProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory>.Get() => this;
		global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService DisposableProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService>.Get() => this;
		global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider DisposableProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider>.Get() => this;
		global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService DisposableProvider.IResolver<global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService>.Get() => this;
		public bool IsService(global::System.Type serviceType) => IsKeyedService(serviceType, null);
		public bool IsKeyedService(global::System.Type serviceType, object? serviceKey) => Resolve(serviceType, serviceKey, true) != null || (serviceKey == null ? Fallback is global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsService s && s.IsService(serviceType) : Fallback is global::Microsoft.Extensions.DependencyInjection.IServiceProviderIsKeyedService k && k.IsKeyedService(serviceType, serviceKey));
		public Scope CreateScope() => new Scope(_root);
		global::Microsoft.Extensions.DependencyInjection.IServiceScope global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory.CreateScope() => CreateScope();

		private static T Required<T>(object? service) => service is T t ? t : throw new global::System.InvalidOperationException("No service for type '" + typeof(T) + "' has been registered.");
		private T Track<T>(T service)
		{
			if (service is global::System.IDisposable) lock (_lock) (_disposables ??= new global::System.Collections.Generic.List<object>()).Add(service);
			return service;
		}
		private object[] Drain() { lock (_lock) { var items = _disposables?.ToArray() ?? new object[0]; _disposables = null; global::System.Array.Reverse(items); return items; } }
		public void Dispose() { foreach (var item in Drain()) (item as global::System.IDisposable ?? throw new global::System.InvalidOperationException("'" + item.GetType() + "' only implements IAsyncDisposable, use DisposeAsync.")).Dispose(); }
	}
}
