name: 🧪 test

on:
  workflow_call:

jobs:
  test:
    name: 🧪 Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        roslyn: ["3.11", "4.0", "4.4"]
    steps:
      - name: 🛒 Check-out code
        uses: actions/checkout@v6

      - name: 📐 Setup .NET Core SDK
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: src/global.json

      - name: 🔍 Enable problem matchers
        run: echo "::add-matcher::.github/matchers/dotnet.json"

      - name: 🛠️ Build code
        run: dotnet build --configuration Release

      - name: 🧪 Testing ${{ matrix.roslyn }} code
        run: >
          dotnet test
          --configuration Release
          -p:GeneratorVersion=${{ matrix.roslyn }}

      - name: Upload Test Results
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: verify-test-results
          path: |
            **/*.received.*
